# Generated by Django 3.0.5 on 2021-01-31 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('andinasoft', '0044_empresas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='actas_contratos',
            fields=[
                ('id_acta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_acta', models.DateField()),
                ('fecha_aprueba', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='contratos',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('anticipo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_creacion', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Finalizado', 'Finalizado'), ('Anulado', 'Anulado')], max_length=255)),
                ('porcentaje_canje', models.IntegerField()),
                ('empresa_contratante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='andinasoft.empresas')),
            ],
        ),
        migrations.CreateModel(
            name='items_contrato',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('otrosi', models.CharField(blank=True, max_length=255, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildingcontrol.contratos')),
            ],
        ),
        migrations.CreateModel(
            name='proveedores',
            fields=[
                ('id_proveedor', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('doc_rut', models.FileField(upload_to='building_control/proveedores')),
                ('doc_cert_bancaria', models.FileField(upload_to='building_control/proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='tiposobra',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='unidades_medida',
            fields=[
                ('id_unid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='productos_servicios',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('tipo', models.CharField(choices=[('Producto', 'Producto'), ('Servicio', 'Servicio')], max_length=255)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildingcontrol.unidades_medida')),
            ],
        ),
        migrations.CreateModel(
            name='otrosi',
            fields=[
                ('id_otrosi', models.AutoField(primary_key=True, serialize=False)),
                ('num_otrosi', models.IntegerField()),
                ('fecha_crea', models.DateField()),
                ('fecha_aprueba', models.DateField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildingcontrol.contratos')),
                ('usuario_aprueba', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_aprueba_otrosi', to=settings.AUTH_USER_MODEL)),
                ('usuario_crea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_crea_otrosi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='items_recibidos',
            fields=[
                ('id_recibido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildingcontrol.actas_contratos')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buildingcontrol.items_contrato')),
            ],
        ),
        migrations.AddField(
            model_name='items_contrato',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildingcontrol.productos_servicios'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildingcontrol.proveedores'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andinasoft.proyectos'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='tipo_obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildingcontrol.tiposobra'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='usuario_aprueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_aprueba_contrato', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contratos',
            name='usuario_crea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_crea_contrato', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actas_contratos',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buildingcontrol.contratos'),
        ),
        migrations.AddField(
            model_name='actas_contratos',
            name='usuario_aprueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_aprueba_acta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actas_contratos',
            name='usuario_crea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_crea_acta', to=settings.AUTH_USER_MODEL),
        ),
    ]
