# Generated by Django 3.0.5 on 2021-01-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingcontrol', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actas_contratos',
            options={'verbose_name': 'Acta de recibido', 'verbose_name_plural': 'Actas de recibido'},
        ),
        migrations.AlterModelOptions(
            name='contratos',
            options={'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelOptions(
            name='items_contrato',
            options={'verbose_name': 'Item de contrato', 'verbose_name_plural': 'Items de contrato'},
        ),
        migrations.AlterModelOptions(
            name='items_recibidos',
            options={'verbose_name': 'item de acta de recibido', 'verbose_name_plural': 'items de acta de recibido'},
        ),
        migrations.AlterModelOptions(
            name='otrosi',
            options={'verbose_name': 'Otrosi', 'verbose_name_plural': 'Otrosi'},
        ),
        migrations.AlterModelOptions(
            name='productos_servicios',
            options={'verbose_name': 'Producto/Servicio', 'verbose_name_plural': 'Producto/Servicio'},
        ),
        migrations.AlterModelOptions(
            name='proveedores',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='tiposobra',
            options={'verbose_name': 'Tipo de Obra', 'verbose_name_plural': 'Tipos de Obras'},
        ),
        migrations.AlterModelOptions(
            name='unidades_medida',
            options={'verbose_name': 'Unidad de medida', 'verbose_name_plural': 'Unidades de medidas'},
        ),
        migrations.AddField(
            model_name='otrosi',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=255),
        ),
    ]
