# Generated by Django 3.0.5 on 2021-01-31 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingcontrol', '0002_auto_20210131_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='actas_contratos',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=255),
        ),
    ]
