# Generated by Django 3.0.5 on 2021-01-31 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildingcontrol', '0003_actas_contratos_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos_servicios',
            options={'verbose_name': 'Producto/Servicio', 'verbose_name_plural': 'Productos/Servicios'},
        ),
    ]
