# Generated by Django 3.0.5 on 2021-01-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingcontrol', '0004_auto_20210131_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='doc_cert_bancaria',
            field=models.FileField(blank=True, null=True, upload_to='building_control/proveedores'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='doc_rut',
            field=models.FileField(blank=True, null=True, upload_to='building_control/proveedores'),
        ),
    ]
