# Generated by Django 3.0.5 on 2021-02-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingcontrol', '0005_auto_20210131_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos',
            name='empresa_contratante',
        ),
        migrations.AddField(
            model_name='items_contrato',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
