# Generated by Django 3.0.5 on 2021-02-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingcontrol', '0009_actas_contratos_anticipo_amortizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='actas_contratos',
            name='num_acta',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='actas_contratos',
            unique_together={('contrato', 'num_acta')},
        ),
    ]
