# Generated by Django 3.0.5 on 2021-02-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingcontrol', '0010_auto_20210202_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='actas_contratos',
            name='canje_efectuado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
