# Generated by Django 3.0.5 on 2021-02-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingcontrol', '0011_actas_contratos_canje_efectuado'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='contrato_docs',
            field=models.FileField(blank=True, null=True, upload_to='contratos_obra'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='anticipo',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
