# Generated by Django 3.0.5 on 2021-02-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingcontrol', '0012_auto_20210202_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='descripcion',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
