# Generated by Django 3.0.5 on 2021-02-10 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildingcontrol', '0013_contratos_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='otrosi',
            name='canje',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items_contrato',
            name='otrosi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildingcontrol.otrosi'),
        ),
    ]
