# Generated by Django 3.0.5 on 2021-02-11 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buildingcontrol', '0014_auto_20210209_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otrosi',
            name='fecha_aprueba',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otrosi',
            name='usuario_aprueba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_aprueba_otrosi', to=settings.AUTH_USER_MODEL),
        ),
    ]
