# Generated by Django 3.0.5 on 2021-02-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingcontrol', '0015_auto_20210211_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='otrosi',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
