# Generated by Django 3.0.5 on 2021-02-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingcontrol', '0016_otrosi_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='otrosi',
            name='descripcion',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
