# Generated by Django 3.0.5 on 2021-02-15 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0044_empresas'),
        ('buildingcontrol', '0017_otrosi_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='pagos_obras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildingcontrol.contratos')),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='andinasoft.Pagos')),
            ],
            options={
                'verbose_name': 'Pago de obra',
                'verbose_name_plural': 'Pagos de obra',
            },
        ),
    ]
