# Generated by Django 3.0.5 on 2021-02-15 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0044_empresas'),
        ('buildingcontrol', '0018_pagos_obras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos_obras',
            name='id',
        ),
        migrations.AlterField(
            model_name='pagos_obras',
            name='pago',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='andinasoft.Pagos'),
        ),
    ]
