# Generated by Django 3.0.5 on 2021-02-17 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0046_facturas_origen'),
        ('buildingcontrol', '0019_auto_20210215_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='empresa_contrata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='andinasoft.empresas'),
        ),
    ]
