# Generated by Django 3.0.5 on 2021-02-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingcontrol', '0020_contratos_empresa_contrata'),
    ]

    operations = [
        migrations.AddField(
            model_name='actas_contratos',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
