# Generated by Django 3.0.5 on 2021-02-18 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0046_facturas_origen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buildingcontrol', '0021_actas_contratos_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='bitacora',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_bitacora', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('observaciones', models.CharField(max_length=2000)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='buildingcontrol.tiposobra')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='andinasoft.proyectos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitacora',
                'verbose_name_plural': 'Bitacoras',
            },
        ),
    ]
