# Generated by Django 3.0.5 on 2021-02-18 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildingcontrol', '0022_bitacora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacora',
            name='obra',
        ),
    ]
