# Generated by Django 3.0.5 on 2021-02-23 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildingcontrol', '0023_remove_bitacora_obra'),
    ]

    operations = [
        migrations.CreateModel(
            name='fotos_bitacora',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to='fotos_bitacora')),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildingcontrol.bitacora')),
            ],
            options={
                'verbose_name': 'Fotos Bitacora',
                'verbose_name_plural': 'Fotos Bitacoras',
            },
        ),
    ]
