# Generated by Django 3.0.5 on 2021-02-25 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildingcontrol', '0024_fotos_bitacora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos',
            name='tipo_obra',
        ),
        migrations.AddField(
            model_name='items_contrato',
            name='tipo_obra',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='buildingcontrol.tiposobra'),
            preserve_default=False,
        ),
    ]
