# Generated by Django 3.0.5 on 2021-02-27 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildingcontrol', '0025_auto_20210225_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='retenciones',
            fields=[
                ('id_rte', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Retencion',
                'verbose_name_plural': 'Retenciones',
            },
        ),
        migrations.AlterField(
            model_name='contratos',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Anulado', 'Anulado')], max_length=255),
        ),
        migrations.AddField(
            model_name='contratos',
            name='retencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='buildingcontrol.retenciones'),
        ),
    ]
