# Generated by Django 3.0.5 on 2021-02-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingcontrol', '0026_auto_20210227_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retenciones',
            name='descripcion',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
