# Generated by Django 3.0.5 on 2021-02-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingcontrol', '0027_auto_20210227_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='actas_contratos',
            name='retencion_efectuada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
