# Generated by Django 3.0.5 on 2021-03-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingcontrol', '0030_auto_20210302_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='total_costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
