# Generated by Django 3.0.5 on 2021-03-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingcontrol', '0031_contratos_total_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='total_costo',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
