# Generated by Django 3.0.5 on 2021-03-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingcontrol', '0032_auto_20210302_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='otrosi',
            name='total_otrosi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
