# Generated by Django 3.0.5 on 2021-03-03 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0048_auto_20210222_1228'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buildingcontrol', '0033_otrosi_total_otrosi'),
    ]

    operations = [
        migrations.CreateModel(
            name='requisiciones',
            fields=[
                ('id_req', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('fech_aprueba', models.DateTimeField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Cruzado', 'Cruzado')], max_length=255)),
                ('orden_cruce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='buildingcontrol.contratos')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='andinasoft.proyectos')),
                ('usuario_aprueba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_aprueba_req', to=settings.AUTH_USER_MODEL)),
                ('usuario_crea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_crea_req', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requisicion',
                'verbose_name_plural': 'Requisiciones',
            },
        ),
        migrations.CreateModel(
            name='items_requisiciones',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildingcontrol.productos_servicios')),
                ('requisicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildingcontrol.requisiciones')),
                ('tipo_obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buildingcontrol.tiposobra')),
            ],
            options={
                'verbose_name': 'Item requisicion',
                'verbose_name_plural': 'Items requisiciones',
            },
        ),
    ]
