# Generated by Django 3.0.5 on 2021-03-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingcontrol', '0034_items_requisiciones_requisiciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisiciones',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
