# Generated by Django 3.0.5 on 2021-03-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingcontrol', '0035_requisiciones_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisiciones',
            name='fech_aprueba',
        ),
        migrations.AddField(
            model_name='requisiciones',
            name='fecha_aprueba',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
