# Generated by Django 3.0.5 on 2021-04-07 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0048_auto_20210222_1228'),
        ('buildingcontrol', '0037_auto_20210309_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos_obras',
            name='item_informe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='andinasoft.ItemsInforme'),
        ),
        migrations.AddField(
            model_name='pagos_obras',
            name='proyecto_asume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='andinasoft.proyectos'),
        ),
    ]
