# Generated by Django 3.0.5 on 2021-04-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingcontrol', '0038_auto_20210406_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='parametros',
            fields=[
                ('id_parametro', models.AutoField(primary_key=True, serialize=False)),
                ('parametro', models.CharField(max_length=255, unique=True)),
                ('check', models.BooleanField(blank=True, help_text='Esta casilla se usa solo cuando el parametro es de tipo Activado/Desactivado', null=True)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Usa este campo cuando el parametro sea un valor especifico', max_digits=15)),
            ],
        ),
    ]
