# Generated by Django 3.0.5 on 2021-04-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingcontrol', '0039_parametros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametros',
            options={'verbose_name': 'Parametro', 'verbose_name_plural': 'Parametros'},
        ),
        migrations.AlterField(
            model_name='parametros',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Usa este campo cuando el parametro sea un valor especifico', max_digits=15, null=True),
        ),
    ]
