# Generated by Django 3.2.16 on 2026-03-03 20:16

import andina.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingcontrol', '0040_auto_20210430_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='contrato_docs',
            field=models.FileField(blank=True, null=True, storage=andina.storage_backends.LocalMediaStorage(), upload_to='contratos_obra'),
        ),
        migrations.AlterField(
            model_name='fotos_bitacora',
            name='foto',
            field=models.ImageField(storage=andina.storage_backends.LocalMediaStorage(), upload_to='fotos_bitacora'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='doc_cert_bancaria',
            field=models.FileField(blank=True, null=True, storage=andina.storage_backends.LocalMediaStorage(), upload_to='building_control/proveedores'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='doc_rut',
            field=models.FileField(blank=True, null=True, storage=andina.storage_backends.LocalMediaStorage(), upload_to='building_control/proveedores'),
        ),
    ]
