# Generated by Django 3.0.5 on 2020-05-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asesores',
            fields=[
                ('cedula', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('banco', models.CharField(max_length=255, null=True)),
                ('cuenta', models.CharField(max_length=255, null=True)),
                ('rut', models.BooleanField(default=0)),
                ('cc', models.BooleanField(default=0)),
                ('direccion', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('estado_civil', models.CharField(max_length=255)),
                ('nivel_educativo', models.CharField(max_length=255)),
                ('equipo', models.CharField(max_length=255, null=True)),
                ('estado', models.CharField(default='Activo', max_length=255, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('fecha_baja', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='departamentos_municipios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
            ],
        ),
    ]
