# Generated by Django 3.0.5 on 2020-05-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='entidades_bancarias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=255)),
                ('codigo', models.IntegerField()),
            ],
        ),
    ]
