# Generated by Django 3.0.5 on 2020-05-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0002_entidades_bancarias'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesores',
            name='telefono',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asesores',
            name='banco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asesores',
            name='cuenta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asesores',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
