# Generated by Django 3.0.5 on 2020-05-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0003_auto_20200515_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('idTercero', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombrecompleto', models.CharField(max_length=255)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('celular1', models.CharField(max_length=255)),
                ('celular2', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono1', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono2', models.CharField(blank=True, max_length=255, null=True)),
                ('domicilio', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('oficina', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nac', models.DateField()),
                ('ocupacion', models.CharField(max_length=255)),
                ('hijos', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_educativo', models.CharField(max_length=255)),
                ('estado_civil', models.CharField(max_length=255)),
                ('nivel_ingresos', models.CharField(max_length=255)),
                ('vehiculo', models.CharField(max_length=255)),
                ('vivienda', models.CharField(max_length=255)),
                ('pasatiempos', models.CharField(blank=True, max_length=255, null=True)),
                ('id_conyuge', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_cony', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido_cony', models.CharField(blank=True, max_length=255, null=True)),
                ('celular_cony', models.CharField(blank=True, max_length=255, null=True)),
                ('email_cony', models.CharField(blank=True, max_length=255, null=True)),
                ('fechanac_cony', models.CharField(blank=True, max_length=255, null=True)),
                ('ocupacion_cony', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_actualizacion', models.DateField()),
            ],
        ),
    ]
