# Generated by Django 3.0.5 on 2020-05-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0005_adjudicacion_documentos_contratos_inmuebles_nuevodatosrecaudos_proyectos_recaudos_vista_adjudicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
