# Generated by Django 3.0.5 on 2020-05-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0007_auto_20200521_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='formas_pago',
            fields=[
                ('descripcion', models.CharField(db_column='descripcion', max_length=255, primary_key=True, serialize=False)),
                ('cuenta_banco', models.CharField(db_column='cuenta_banco', max_length=255)),
                ('cuenta_contable', models.CharField(db_column='cuenta_contable', max_length=255)),
            ],
            options={
                'db_table': 'formas_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='saldos_adj',
            fields=[
                ('adj', models.CharField(db_column='adj', max_length=255)),
                ('tipocta', models.CharField(db_column='tipocta', max_length=255)),
                ('idcta', models.CharField(db_column='idcta', max_length=255, primary_key=True, serialize=False)),
                ('nrocta', models.IntegerField(db_column='nrocta')),
                ('fecha', models.DateField(db_column='fecha')),
                ('capital', models.DecimalField(db_column='capital', decimal_places=2, max_digits=14)),
                ('intcte', models.DecimalField(db_column='intcte', decimal_places=2, max_digits=14)),
                ('cuota', models.DecimalField(db_column='cuota', decimal_places=2, max_digits=14)),
                ('rcdocapital', models.DecimalField(db_column='rcdocapital', decimal_places=2, max_digits=14)),
                ('rcdointcte', models.DecimalField(db_column='rcdointcte', decimal_places=2, max_digits=14)),
                ('rcdointmora', models.DecimalField(db_column='rcdointmora', decimal_places=2, max_digits=14)),
                ('saldocapital', models.DecimalField(db_column='saldocapital', decimal_places=2, max_digits=14)),
                ('saldoint', models.DecimalField(db_column='saldoint', decimal_places=2, max_digits=14)),
                ('saldocuota', models.DecimalField(db_column='saldocuota', decimal_places=2, max_digits=14)),
            ],
            options={
                'db_table': 'saldos_cuotas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='seguimientos',
            fields=[
                ('id_seg', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('adj', models.CharField(db_column='adj', max_length=255)),
                ('fecha', models.DateField(db_column='fecha')),
                ('tipo_seguimiento', models.CharField(db_column='tipo_seguimiento', max_length=255)),
                ('forma_contacto', models.CharField(db_column='forma_contacto', max_length=255)),
                ('respuesta_cliente', models.CharField(db_column='respuesta_cliente', max_length=255)),
                ('valor_compromiso', models.IntegerField(db_column='valor_compromiso', max_length=255)),
                ('fecha_compromiso', models.CharField(db_column='fecha_compromiso', max_length=255)),
                ('usuario', models.CharField(db_column='usuario', max_length=255)),
            ],
            options={
                'db_table': 'seguimientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='timeline',
            fields=[
                ('id_line', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('adj', models.CharField(db_column='adj', max_length=255)),
                ('fecha', models.DateField(db_column='fecha')),
                ('usuario', models.CharField(db_column='usuario', max_length=255)),
                ('accion', models.CharField(db_column='accion', max_length=255)),
            ],
            options={
                'db_table': 'timeline_adj',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='titulares_por_adj',
            fields=[
                ('adj', models.CharField(db_column='IdAdjudicacion', max_length=12, primary_key=True, serialize=False)),
                ('IdTercero1', models.CharField(db_column='IdTercero1', max_length=255)),
                ('IdTercero2', models.CharField(db_column='IdTercero2', max_length=255)),
                ('IdTercero3', models.CharField(db_column='IdTercero3', max_length=255)),
                ('IdTercero4', models.CharField(db_column='IdTercero4', max_length=255)),
                ('titular1', models.CharField(db_column='titular1', max_length=255)),
                ('titular2', models.CharField(db_column='titular2', max_length=255)),
                ('titular3', models.CharField(db_column='titular3', max_length=255)),
                ('titular4', models.CharField(db_column='titular4', max_length=255)),
            ],
            options={
                'db_table': 'titulares_por_adj',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='parametros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='clientes',
            name='celular1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='ciudad',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='domicilio',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='estado_civil',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='fecha_actualizacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='fecha_nac',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='fechanac_cony',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nivel_educativo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nivel_ingresos',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='ocupacion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='vehiculo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='vivienda',
            field=models.CharField(max_length=255),
        ),
    ]
