# Generated by Django 3.0.5 on 2020-06-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0008_auto_20200528_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionComisiones',
            fields=[
                ('id_comision', models.CharField(db_column='Id', max_length=11, primary_key=True, serialize=False)),
                ('idadjudicacion', models.CharField(blank=True, db_column='IdAdjudicacion', max_length=10, null=True)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('idgestor', models.CharField(blank=True, db_column='IdGestor', max_length=12, null=True)),
                ('idcargo', models.CharField(blank=True, db_column='IdCargo', max_length=12, null=True)),
                ('comision', models.DecimalField(blank=True, db_column='Comision', decimal_places=4, max_digits=6, null=True)),
                ('usuario', models.CharField(blank=True, db_column='Usuario', max_length=20, null=True)),
            ],
            options={
                'db_table': 'asignacion_comisiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CargosFijos',
            fields=[
                ('idcargo', models.IntegerField(db_column='idcargo', primary_key=True, serialize=False)),
                ('cc_fija', models.CharField(blank=True, db_column='cc_fijo', max_length=255, null=True)),
                ('porc_fijo', models.DecimalField(blank=True, db_column='porc_fijo', decimal_places=2, max_digits=2, null=True)),
            ],
            options={
                'db_table': 'cargos_fijos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='consecutivos',
            fields=[
                ('id_consec', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('documento', models.CharField(db_column='documento', max_length=255)),
                ('consecutivo', models.IntegerField(db_column='consecutivo')),
                ('prefijo', models.CharField(db_column='prefijo', max_length=255)),
            ],
            options={
                'db_table': 'consecutivos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recaudos_general',
            fields=[
                ('idrecaudo', models.IntegerField(db_column='IdRecaudo', primary_key=True, serialize=False)),
                ('idadjudicacion', models.CharField(blank=True, db_column='IdAdjudicacion', max_length=12, null=True)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('numrecibo', models.CharField(db_column='NumRecibo', max_length=12, unique=True)),
                ('idtercero', models.CharField(blank=True, db_column='IdTercero', max_length=12, null=True)),
                ('operacion', models.CharField(db_column='Operacion', max_length=30)),
                ('valor', models.DecimalField(db_column='Valor', decimal_places=2, max_digits=20)),
                ('formapago', models.CharField(blank=True, db_column='FormaPago', max_length=25, null=True)),
            ],
            options={
                'db_table': 'recaudos_general',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecaudosNoradicados',
            fields=[
                ('recibo', models.AutoField(primary_key=True, serialize=False)),
                ('contrato', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.CharField(blank=True, max_length=255, null=True)),
                ('concepto', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recaudos_noradicados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ventas_nuevas',
            fields=[
                ('id_venta', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('id_t1', models.CharField(max_length=255)),
                ('id_t2', models.CharField(blank=True, max_length=255, null=True)),
                ('id_t3', models.CharField(blank=True, max_length=255, null=True)),
                ('id_t4', models.CharField(blank=True, max_length=255, null=True)),
                ('inmueble', models.CharField(max_length=255)),
                ('valor_venta', models.IntegerField()),
                ('forma_pago', models.CharField(blank=True, max_length=255, null=True)),
                ('cuota_inicial', models.IntegerField()),
                ('cant_ci1', models.IntegerField(blank=True, null=True)),
                ('fecha_ci1', models.DateField(blank=True, null=True)),
                ('valor_ci1', models.IntegerField(blank=True, null=True)),
                ('cant_ci2', models.IntegerField(blank=True, null=True)),
                ('fecha_ci2', models.DateField(blank=True, null=True)),
                ('valor_ci2', models.IntegerField(blank=True, null=True)),
                ('cant_ci3', models.IntegerField(blank=True, null=True)),
                ('fecha_ci3', models.DateField(blank=True, null=True)),
                ('valor_ci3', models.IntegerField(blank=True, null=True)),
                ('cant_ci4', models.IntegerField(blank=True, null=True)),
                ('fecha_ci4', models.DateField(blank=True, null=True)),
                ('valor_ci4', models.IntegerField(blank=True, null=True)),
                ('cant_ci5', models.IntegerField(blank=True, null=True)),
                ('fecha_ci5', models.DateField(blank=True, null=True)),
                ('valor_ci5', models.IntegerField(blank=True, null=True)),
                ('cant_ci6', models.IntegerField(blank=True, null=True)),
                ('fecha_ci6', models.DateField(blank=True, null=True)),
                ('valor_ci6', models.IntegerField(blank=True, null=True)),
                ('cant_ci7', models.IntegerField(blank=True, null=True)),
                ('fecha_ci7', models.DateField(blank=True, null=True)),
                ('valor_ci7', models.IntegerField(blank=True, null=True)),
                ('saldo', models.IntegerField(blank=True, null=True)),
                ('forma_saldo', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_ctas_fn', models.IntegerField(blank=True, null=True)),
                ('inicio_fn', models.DateField(blank=True, null=True)),
                ('nro_cuotas_fn', models.IntegerField(blank=True, null=True)),
                ('valor_ctas_ce', models.IntegerField(blank=True, null=True)),
                ('inicio_ce', models.DateField(blank=True, null=True)),
                ('nro_cuotas_ce', models.IntegerField(blank=True, null=True)),
                ('period_ce', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('grupo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_contrato', models.DateField(blank=True, null=True)),
                ('usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'nuevas_ventas',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Nuevodatosrecaudos',
        ),
    ]
