# Generated by Django 3.0.5 on 2020-06-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0009_auto_20200616_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescuentosCondicionados',
            fields=[
                ('idadjudicacion', models.CharField(db_column='idAdjudicacion', max_length=255, primary_key=True, serialize=False)),
                ('fecha_condicion', models.DateField(blank=True, null=True)),
                ('valor_condicion', models.IntegerField(blank=True, null=True)),
                ('valor_dcto', models.IntegerField(blank=True, null=True)),
                ('nueva_ci', models.IntegerField(blank=True, null=True)),
                ('nuevo_saldo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'descuentos_condicionados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanPagos',
            fields=[
                ('idcta', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tipocta', models.CharField(blank=True, max_length=255, null=True)),
                ('nrocta', models.CharField(blank=True, max_length=255, null=True)),
                ('adj', models.CharField(blank=True, max_length=255, null=True)),
                ('capital', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('intcte', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cuota', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plan_pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VerificacionOperaciones',
            fields=[
                ('idadjudicacion', models.CharField(db_column='idAdjudicacion', max_length=255, primary_key=True, serialize=False)),
                ('enmendaduras', models.IntegerField(blank=True, null=True)),
                ('doc_incompleta', models.IntegerField(blank=True, null=True)),
                ('valores_incorrectos', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'verificacion_operaciones',
                'managed': False,
            },
        ),
    ]
