# Generated by Django 3.0.5 on 2020-06-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0010_descuentoscondicionados_planpagos_verificacionoperaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagocomision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comision', models.CharField(db_column='Id', max_length=11)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('idadjudicacion', models.CharField(blank=True, max_length=12, null=True)),
                ('idgestor', models.CharField(blank=True, max_length=12, null=True)),
                ('idcargo', models.CharField(blank=True, max_length=12, null=True)),
                ('tasacomision', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('comision', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('retefuente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dctoanticipo', models.DecimalField(blank=True, db_column='DctoAnticipo', decimal_places=2, max_digits=10, null=True)),
                ('pagoneto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaccion', models.IntegerField(blank=True, null=True)),
                ('veces', models.IntegerField(blank=True, null=True)),
                ('veriact', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pagocomision',
                'managed': False,
            },
        ),
    ]
