# Generated by Django 3.0.5 on 2020-07-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0011_pagocomision'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoCartera',
            fields=[
                ('id_ppto', models.CharField(db_column='Id', max_length=35, primary_key=True, serialize=False)),
                ('proyecto', models.CharField(db_column='Proyecto', max_length=255)),
                ('periodo', models.CharField(blank=True, db_column='Periodo', max_length=255, null=True)),
                ('idadjudicacion', models.CharField(blank=True, db_column='IdAdjudicacion', max_length=22, null=True)),
                ('cliente', models.CharField(blank=True, db_column='Cliente', max_length=120, null=True)),
                ('tipocta', models.CharField(blank=True, db_column='TipoCta', max_length=4, null=True)),
                ('ncta', models.IntegerField(db_column='NCta')),
                ('idcta', models.CharField(db_column='IdCta', max_length=255)),
                ('tipocartera', models.CharField(blank=True, db_column='TipoCartera', max_length=30, null=True)),
                ('fecha', models.DateTimeField(blank=True, db_column='Fecha', null=True)),
                ('capital', models.DecimalField(blank=True, db_column='Capital', decimal_places=2, max_digits=20, null=True)),
                ('interes', models.DecimalField(blank=True, db_column='Interes', decimal_places=2, max_digits=20, null=True)),
                ('cuota', models.DecimalField(blank=True, db_column='Cuota', decimal_places=2, max_digits=20, null=True)),
                ('diasmora', models.IntegerField(blank=True, db_column='DiasMora', null=True)),
                ('mora', models.DecimalField(blank=True, db_column='Mora', decimal_places=2, max_digits=20, null=True)),
                ('asesor', models.CharField(blank=True, db_column='Asesor', max_length=120, null=True)),
                ('usuario', models.CharField(blank=True, db_column='Usuario', max_length=20, null=True)),
                ('fechaoperacion', models.DateField(blank=True, db_column='FechaOperacion', null=True)),
                ('edad', models.CharField(blank=True, db_column='Edad', max_length=50, null=True)),
                ('segmento', models.CharField(blank=True, db_column='Segmento', max_length=200, null=True)),
            ],
            options={
                'db_table': 'presupuesto_cartera',
                'managed': False,
            },
        ),
    ]
