# Generated by Django 3.0.5 on 2020-07-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0012_presupuestocartera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('nroradicado', models.AutoField(db_column='NroRadicado', primary_key=True, serialize=False)),
                ('nrofactura', models.CharField(blank=True, db_column='NroFactura', max_length=255, null=True)),
                ('idtercero', models.CharField(blank=True, db_column='idTercero', max_length=255, null=True)),
                ('nombretercero', models.CharField(blank=True, db_column='NombreTercero', max_length=255, null=True)),
                ('empresa', models.CharField(blank=True, db_column='Empresa', max_length=255, null=True)),
                ('valor', models.IntegerField(blank=True, db_column='Valor', null=True)),
                ('pago_neto', models.IntegerField(blank=True, db_column='PagoNeto', null=True)),
                ('fechavenc', models.DateField(blank=True, db_column='FechaVenc', null=True)),
                ('nrocausa', models.CharField(blank=True, db_column='NroCausa', max_length=255, null=True)),
                ('fechacausa', models.DateField(blank=True, db_column='FechaCausa', null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peticiones',
            fields=[
                ('nroradicado', models.AutoField(db_column='NroRadicado', primary_key=True, serialize=False)),
                ('idcliente', models.CharField(blank=True, db_column='idCliente', max_length=255, null=True)),
                ('nombrecliente', models.CharField(blank=True, db_column='NombreCliente', max_length=255, null=True)),
                ('proyecto', models.CharField(blank=True, db_column='Proyecto', max_length=255, null=True)),
                ('tiporeq', models.CharField(blank=True, db_column='TipoReq', max_length=255, null=True)),
                ('adj', models.CharField(blank=True, db_column='Adj', max_length=255, null=True)),
                ('carteraadj', models.CharField(blank=True, db_column='CarteraAdj', max_length=255, null=True)),
                ('estadoadj', models.CharField(blank=True, db_column='EstadoAdj', max_length=255, null=True)),
                ('vencimiento', models.DateField(blank=True, db_column='Vencimiento', null=True)),
                ('estadoenvio', models.CharField(blank=True, db_column='EstadoEnvio', max_length=255, null=True)),
                ('fecharespuesta', models.DateField(blank=True, db_column='FechaRespuesta', null=True)),
                ('formaenviorta', models.CharField(blank=True, db_column='FormaEnvioRta', max_length=255, null=True)),
                ('fechaenviorta', models.DateField(blank=True, db_column='FechaEnvioRta', null=True)),
                ('fechaconfirrta', models.DateField(blank=True, db_column='FechaConfirRta', null=True)),
                ('nroguia', models.CharField(blank=True, db_column='NroGuia', max_length=255, null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='timeline_radicados',
            fields=[
                ('id_flow', models.AutoField(db_column='id_flow', primary_key=True, serialize=False)),
                ('nroradicado', models.CharField(blank=True, db_column='NroRadicado', max_length=255, null=True)),
                ('usuario_entrega', models.CharField(blank=True, db_column='Usuario_entrega', max_length=255, null=True)),
                ('usuario_recibe', models.CharField(blank=True, db_column='Usuario_recibe', max_length=255, null=True)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
            ],
        ),
    ]
