# Generated by Django 3.0.5 on 2020-07-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0013_facturas_peticiones_timeline_radicados'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='fechradicado',
            field=models.DateField(blank=True, db_column='FechaRadica', null=True),
        ),
        migrations.AddField(
            model_name='peticiones',
            name='fechradicado',
            field=models.DateField(blank=True, db_column='FechaRadica', null=True),
        ),
    ]
