# Generated by Django 3.0.5 on 2020-07-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0014_auto_20200710_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturas',
            old_name='fechradicado',
            new_name='fecharadicado',
        ),
        migrations.RenameField(
            model_name='peticiones',
            old_name='fechradicado',
            new_name='fecharadicado',
        ),
        migrations.RemoveField(
            model_name='timeline_radicados',
            name='usuario_entrega',
        ),
        migrations.RemoveField(
            model_name='timeline_radicados',
            name='usuario_recibe',
        ),
        migrations.AddField(
            model_name='timeline_radicados',
            name='accion',
            field=models.CharField(blank=True, db_column='Accion', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timeline_radicados',
            name='usuario',
            field=models.CharField(blank=True, db_column='Usuario', max_length=255, null=True),
        ),
    ]
