# Generated by Django 3.0.5 on 2020-07-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0015_auto_20200710_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='fechafactura',
            field=models.DateField(blank=True, db_column='FechaFactura', null=True),
        ),
    ]
