# Generated by Django 3.0.5 on 2020-07-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0016_facturas_fechafactura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('idpago', models.AutoField(db_column='IdPago', primary_key=True, serialize=False)),
                ('nroradicado', models.IntegerField(blank=True, db_column='NroRadicado', null=True)),
                ('valor', models.IntegerField(blank=True, db_column='Valorpago', null=True)),
                ('fechapago', models.DateField(blank=True, db_column='Fechapago', null=True)),
                ('formapago', models.CharField(blank=True, db_column='FormaPago', max_length=255, null=True)),
            ],
        ),
    ]
