# Generated by Django 3.0.5 on 2020-07-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0017_pagos'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuentas_pagos',
            fields=[
                ('idcuenta', models.AutoField(db_column='Idcuenta', primary_key=True, serialize=False)),
                ('empresa', models.CharField(blank=True, db_column='Empresa', max_length=255, null=True)),
                ('cuentabanco', models.CharField(blank=True, db_column='Cuentabanco', max_length=255, null=True)),
                ('cuentacontable', models.CharField(blank=True, db_column='Cuentacontable', max_length=255, null=True)),
            ],
        ),
    ]
