# Generated by Django 3.0.5 on 2020-07-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0018_cuentas_pagos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='empresapago',
            field=models.CharField(blank=True, db_column='EmpresaPago', max_length=255, null=True),
        ),
    ]
