# Generated by Django 3.0.5 on 2020-07-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0019_pagos_empresapago'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline_radicados',
            name='tiporadicado',
            field=models.CharField(blank=True, db_column='TipoRadicado', max_length=255, null=True),
        ),
    ]
