# Generated by Django 3.0.5 on 2020-07-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0020_timeline_radicados_tiporadicado'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoCartera',
            fields=[
                ('idadjudicacion', models.CharField(db_column='IdAdjudicacion', max_length=255, primary_key=True, serialize=False)),
                ('gestorasignado', models.CharField(blank=True, db_column='GestorAsignado', max_length=255, null=True)),
                ('segmento', models.CharField(blank=True, db_column='Segmento', max_length=255, null=True)),
                ('accionrecomendada', models.CharField(blank=True, db_column='AccionRecomendada', max_length=255, null=True)),
            ],
            options={
                'db_table': 'info_cartera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Promesas',
            fields=[
                ('idadjudicacion', models.CharField(db_column='idAdjudicacion', max_length=255, primary_key=True, serialize=False)),
                ('nropromesa', models.CharField(blank=True, db_column='NroPromesa', max_length=255, null=True)),
                ('fechapromesa', models.DateField(blank=True, db_column='FechaPromesa', null=True)),
                ('fechaentrega', models.DateField(blank=True, db_column='FechaEntrega', null=True)),
                ('fechaescritura', models.DateField(blank=True, db_column='FechaEscritura', null=True)),
                ('formapago', models.CharField(blank=True, db_column='FormaPago', max_length=255, null=True)),
                ('formaci', models.CharField(blank=True, db_column='FormaCI', max_length=255, null=True)),
                ('formasaldo', models.CharField(blank=True, db_column='FormaSaldo', max_length=255, null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=255, null=True)),
                ('entregado', models.DateField(blank=True, db_column='Entregado', null=True)),
                ('escriturado', models.DateField(blank=True, db_column='Escriturado', null=True)),
                ('usuariocrea', models.CharField(blank=True, db_column='UsuarioCrea', max_length=255, null=True)),
                ('usuarioaprueba', models.CharField(blank=True, db_column='UsuarioAprueba', max_length=255, null=True)),
                ('fechaaprueba', models.DateField(blank=True, db_column='FechaAprueba', max_length=255, null=True)),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, db_column='Ciudad', max_length=255, null=True)),
            ],
            options={
                'db_table': 'promesas',
                'managed': False,
            },
        ),
    ]
