# Generated by Django 3.0.5 on 2020-08-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0021_infocartera_promesas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsInforme',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('grupo', models.CharField(blank=True, db_column='Grupo', max_length=30, null=True)),
                ('temas', models.CharField(blank=True, db_column='Item', max_length=1000, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GastosInforme',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('empresa', models.CharField(db_column='Empresa', max_length=255)),
                ('cuenta', models.CharField(blank=True, db_column='Cuenta', max_length=255, null=True)),
                ('descrip_cuenta', models.CharField(blank=True, db_column='DescripcionCuenta', max_length=255, null=True)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('comprobante', models.CharField(db_column='Comprobante', max_length=255)),
                ('tercero', models.CharField(blank=True, db_column='Tercero', max_length=255, null=True)),
                ('descrip_gasto', models.CharField(blank=True, db_column='DescripcionGasto', max_length=255, null=True)),
                ('valor', models.DecimalField(blank=True, db_column='Valor', decimal_places=2, max_digits=10, null=True)),
                ('proyecto', models.CharField(blank=True, db_column='Proyecto', max_length=255, null=True)),
                ('centro_costo', models.CharField(blank=True, db_column='CentroCosto', max_length=255, null=True)),
                ('item_asociado', models.CharField(blank=True, db_column='ItemAsociado', max_length=255, null=True)),
            ],
            options={
                'managed': True,
                'unique_together': {('comprobante', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='CuentasAsociadas',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('empresa', models.CharField(blank=True, db_column='Empresa', max_length=255, null=True)),
                ('cuenta', models.CharField(blank=True, db_column='Cuenta', max_length=255, null=True)),
                ('descrip_cuenta', models.CharField(blank=True, db_column='Descripcion_Cuenta', max_length=255, null=True)),
                ('item_asociado', models.CharField(blank=True, db_column='Item_Asociado', max_length=255, null=True)),
            ],
            options={
                'managed': True,
                'unique_together': {('empresa', 'cuenta')},
            },
        ),
    ]
