# Generated by Django 3.0.5 on 2020-08-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0022_cuentasasociadas_gastosinforme_itemsinforme'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentrosCostos',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('empresa', models.CharField(db_column='Empresa', max_length=255)),
                ('idcentrocosto', models.CharField(db_column='IdCentroCosto', max_length=255)),
                ('centro', models.CharField(db_column='CentroCosto', max_length=255)),
                ('subcentro', models.CharField(blank=True, db_column='SubcentroCosto', max_length=255, null=True)),
                ('proyecto', models.CharField(blank=True, db_column='Proyecto', max_length=255, null=True)),
                ('detalle', models.CharField(blank=True, db_column='Detalle', max_length=255, null=True)),
            ],
            options={
                'managed': True,
                'unique_together': {('idcentrocosto', 'empresa')},
            },
        ),
    ]
