# Generated by Django 3.0.5 on 2020-09-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0023_centroscostos'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaManzanas',
            fields=[
                ('manzana', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('meses', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entrega_manzanas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parametros_Operaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parametros',
                'managed': False,
            },
        ),
    ]
