# Generated by Django 3.0.5 on 2020-11-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0024_entregamanzanas_parametros_operaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='ciudad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nivel_ingresos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='vehiculo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='vivienda',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
