# Generated by Django 3.0.5 on 2020-12-05 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('andinasoft', '0025_auto_20201126_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios_Proyectos',
            fields=[
                ('id_rel', models.AutoField(primary_key=True, serialize=False)),
                ('proyecto', models.ManyToManyField(to='andinasoft.proyectos')),
                ('usuario', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
