# Generated by Django 3.0.5 on 2020-12-05 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('andinasoft', '0026_usuarios_proyectos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios_proyectos',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='usuarios_proyectos',
            name='proyecto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='andinasoft.proyectos'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='usuarios_proyectos',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuarios_proyectos',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
