# Generated by Django 3.0.5 on 2020-12-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0027_auto_20201205_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios_proyectos',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='usuarios_proyectos',
            name='proyecto',
            field=models.ManyToManyField(to='andinasoft.proyectos'),
        ),
    ]
