# Generated by Django 3.0.5 on 2021-01-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0028_auto_20201205_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pqrs',
            fields=[
                ('id_pqrs', models.AutoField(primary_key=True, serialize=False)),
                ('idadjudicacion', models.CharField(blank=True, db_column='idAdjudicacion', max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_radicado', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_respuesta', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
                ('req_respuesta', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_respuesta', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_peticion', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_respuesta', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_envio', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario_radica', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario_cierra', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'pqrs',
                'managed': False,
            },
        ),
    ]
