# Generated by Django 3.0.5 on 2021-01-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0029_pqrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesores',
            name='tipo_cuenta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
