# Generated by Django 3.0.5 on 2021-01-14 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0030_asesores_tipo_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesores',
            name='acceso_online',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Gtt',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('proyecto', models.CharField(blank=True, max_length=255, null=True)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andinasoft.asesores')),
            ],
        ),
    ]
