# Generated by Django 3.0.5 on 2021-01-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0031_auto_20210114_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesores',
            name='cert_banc',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='asesores',
            name='acceso_online',
            field=models.BooleanField(default=1),
        ),
    ]
