# Generated by Django 3.0.5 on 2021-01-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0032_auto_20210115_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gtt',
            name='fecha',
        ),
        migrations.AddField(
            model_name='gtt',
            name='estado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gtt',
            name='fecha_desde',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gtt',
            name='fecha_hasta',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
    ]
