# Generated by Django 3.0.5 on 2021-01-16 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0033_auto_20210115_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gtt',
            name='asesor',
        ),
        migrations.CreateModel(
            name='Detalle_gtt',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andinasoft.asesores')),
                ('gtt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andinasoft.Gtt')),
            ],
        ),
    ]
