# Generated by Django 3.0.5 on 2021-01-16 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0034_auto_20210115_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_gtt',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='gtt',
            options={'managed': True},
        ),
    ]
