# Generated by Django 3.0.5 on 2021-01-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0035_auto_20210115_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtt',
            name='usuario_aprueba',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gtt',
            name='usuario_crea',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
