# Generated by Django 3.0.5 on 2021-01-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0036_auto_20210116_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesores',
            name='tipo_asesor',
            field=models.CharField(default='Externo', max_length=255),
            preserve_default=False,
        ),
    ]
