# Generated by Django 3.0.5 on 2021-01-26 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0038_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatars',
            fields=[
                ('id_avatar', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='profiles',
            name='avatar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='andinasoft.Avatars'),
            preserve_default=False,
        ),
    ]
