# Generated by Django 3.0.5 on 2021-01-27 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0039_auto_20210126_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatars',
            name='image',
            field=models.ImageField(upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='avatars',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='avatar',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.PROTECT, to='andinasoft.Avatars'),
        ),
    ]
