# Generated by Django 3.0.5 on 2021-01-27 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0040_auto_20210127_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='avatar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='andinasoft.Avatars'),
        ),
    ]
