# Generated by Django 3.0.5 on 2021-01-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0042_auto_20210127_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastosinforme',
            name='valor',
            field=models.DecimalField(blank=True, db_column='Valor', decimal_places=2, max_digits=20, null=True),
        ),
    ]
