# Generated by Django 3.0.5 on 2021-01-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0043_auto_20210131_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='empresas',
            fields=[
                ('Nit', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('representante_legal', models.CharField(max_length=255)),
                ('cc_replegal', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='logos_empresas')),
            ],
        ),
    ]
