# Generated by Django 3.0.5 on 2021-02-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0044_empresas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='nroradicado',
            field=models.CharField(blank=True, db_column='NroRadicado', max_length=255, null=True),
        ),
    ]
