# Generated by Django 3.0.5 on 2021-02-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0045_auto_20210215_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='origen',
            field=models.CharField(blank=True, db_column='Origen', default='Radicado', max_length=255, null=True),
        ),
    ]
