# Generated by Django 3.0.5 on 2021-02-19 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('andinasoft', '0046_facturas_origen'),
    ]

    operations = [
        migrations.CreateModel(
            name='notificaciones_correo',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('identificador', models.CharField(max_length=255, unique=True)),
                ('users_to_send', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificacion email',
                'verbose_name_plural': 'Notificaciones email',
            },
        ),
    ]
