# Generated by Django 3.0.5 on 2021-02-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0047_notificaciones_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='oficina',
            field=models.CharField(blank=True, choices=[('MONTERIA', 'MONTERIA'), ('MEDELLIN', 'MEDELLIN')], db_column='Oficina', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facturas',
            name='usuario',
            field=models.CharField(blank=True, db_column='Usuario', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagos',
            name='usuario',
            field=models.CharField(blank=True, db_column='Usuario', max_length=255, null=True),
        ),
    ]
