# Generated by Django 3.0.5 on 2021-05-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0051_auto_20210512_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egresos_contable',
            name='conciliacion',
        ),
        migrations.RemoveField(
            model_name='egresos_contable',
            name='cuenta',
        ),
        migrations.RemoveField(
            model_name='egresos_contable',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='egresos_contable',
            name='pago_asociado',
        ),
        migrations.RemoveField(
            model_name='egresos_contable',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='planilla_movimiento',
            name='cuenta',
        ),
        migrations.RemoveField(
            model_name='planilla_movimiento',
            name='usuario_cierra',
        ),
        migrations.DeleteModel(
            name='conciliaciones',
        ),
        migrations.DeleteModel(
            name='egresos_banco',
        ),
        migrations.DeleteModel(
            name='egresos_contable',
        ),
        migrations.DeleteModel(
            name='planilla_movimiento',
        ),
    ]
