# Generated by Django 3.0.5 on 2021-05-12 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0052_auto_20210512_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentas_pagos',
            name='nit_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='andinasoft.empresas'),
        ),
    ]
