# Generated by Django 3.0.5 on 2021-07-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0053_cuentas_pagos_nit_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentas_pagos',
            name='doc_contable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cuentas_pagos',
            name='nro_cuentacontable',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
