# Generated by Django 3.0.5 on 2022-03-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0054_auto_20210724_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos_comisiones',
            fields=[
                ('idcargo', models.IntegerField(db_column='IdCarg', primary_key=True, serialize=False)),
                ('nombrecargo', models.CharField(blank=True, db_column='NombreCargo', max_length=100, null=True)),
            ],
            options={
                'db_table': 'cargos_comisiones',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='asesores',
            name='afiliaciones',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='asesores',
            name='hv',
            field=models.BooleanField(default=0),
        ),
    ]
