# Generated by Django 3.2.13 on 2022-07-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0055_auto_20220301_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesores',
            name='tipo_asesor',
            field=models.CharField(choices=[('Interno', 'Interno'), ('Externo', 'Externo')], help_text='Para que un asesor sea visible en GTT debe estar marcado como Externo', max_length=255),
        ),
    ]
