# Generated by Django 3.2.13 on 2022-08-22 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('andinasoft', '0056_alter_asesores_tipo_asesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='bk_bfchangeplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_bk', models.DateTimeField(auto_now=True)),
                ('adj', models.CharField(blank=True, max_length=255, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='andinasoft.proyectos')),
                ('usuario_bk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bk_recaudodetallado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recibo', models.CharField(blank=True, db_column='Recibo', max_length=12, null=True)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('idcta', models.CharField(blank=True, db_column='IdCta', max_length=20, null=True)),
                ('idadjudicacion', models.CharField(blank=True, db_column='IdAdjudicacion', max_length=12, null=True)),
                ('capital', models.DecimalField(blank=True, db_column='Capital', decimal_places=2, max_digits=16, null=True)),
                ('interescte', models.DecimalField(blank=True, db_column='InteresCte', decimal_places=2, max_digits=16, null=True)),
                ('interesmora', models.DecimalField(blank=True, db_column='InteresMora', decimal_places=2, max_digits=16, null=True)),
                ('moralqd', models.DecimalField(blank=True, db_column='MoraLqd', decimal_places=2, max_digits=16, null=True)),
                ('fechaoperacion', models.DateField(blank=True, db_column='FechaOperacion', null=True)),
                ('usuario', models.CharField(blank=True, db_column='Usuario', max_length=12, null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=20, null=True)),
                ('id_bk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andinasoft.bk_bfchangeplan')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='andinasoft.proyectos')),
            ],
        ),
        migrations.CreateModel(
            name='bk_planpagos',
            fields=[
                ('idcta', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tipocta', models.CharField(blank=True, max_length=255, null=True)),
                ('nrocta', models.IntegerField(blank=True, null=True)),
                ('adj', models.CharField(blank=True, max_length=255, null=True)),
                ('capital', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('intcte', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cuota', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('id_bk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andinasoft.bk_bfchangeplan')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='andinasoft.proyectos')),
            ],
        ),
    ]
