# Generated by Django 3.2.16 on 2022-12-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0057_bk_bfchangeplan_bk_planpagos_bk_recaudodetallado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='bk_planpagos',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bk_planpagos',
            name='idcta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
