# Generated by Django 3.2.20 on 2023-07-18 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0059_cities_countries_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIUU',
            fields=[
                ('codigo', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Codigo CIUU',
                'verbose_name_plural': 'Codigos CIUU',
            },
        ),
        migrations.AddField(
            model_name='clientes',
            name='fecha_exp_id',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='lugar_exp_id',
            field=models.CharField(blank=True, choices=[('13', 'Cédula de ciudadanía'), ('31', 'NIT'), ('22', 'Cédula de extranjería'), ('42', 'Documento de identificación extranjero'), ('50', 'NIT de otro país'), ('91', 'NUIP'), ('41', 'Pasaporte'), ('47', 'Permiso especial de permanencia PEP'), ('21', 'Tarjeta de extranjería'), ('R-00-PN', 'No obligado a registrarse en el RUT PN')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='lugar_nac',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='tipo_doc',
            field=models.CharField(blank=True, choices=[('13', 'Cédula de ciudadanía'), ('31', 'NIT'), ('22', 'Cédula de extranjería'), ('42', 'Documento de identificación extranjero'), ('50', 'NIT de otro país'), ('91', 'NUIP'), ('41', 'Pasaporte'), ('47', 'Permiso especial de permanencia PEP'), ('21', 'Tarjeta de extranjería'), ('R-00-PN', 'No obligado a registrarse en el RUT PN')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='ocupacion',
            field=models.CharField(blank=True, choices=[('DEPENDIENTE', 'Dependiente'), ('INDEPENDIENTE', 'Independiente'), ('EMPLEADO PUBLICO', 'Empleado Público'), ('PENSIONADO', 'Pensionado'), ('FUERZA PUBLICA', 'Miembro Fuerza Publica'), ('OTRO', 'Otro')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='ocupacion_cony',
            field=models.CharField(blank=True, choices=[('DEPENDIENTE', 'Dependiente'), ('INDEPENDIENTE', 'Independiente'), ('EMPLEADO PUBLICO', 'Empleado Público'), ('PENSIONADO', 'Pensionado'), ('FUERZA PUBLICA', 'Miembro Fuerza Publica'), ('OTRO', 'Otro')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='vivienda',
            field=models.CharField(blank=True, choices=[('PROPIA', 'Propia'), ('FAMILIAR', 'Familiar'), ('ARRENDADA', 'Arrendada')], max_length=255, null=True),
        ),
    ]
