# Generated by Django 3.2.16 on 2023-08-16 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0060_auto_20230718_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='andinasoft.cities'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='andinasoft.states'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='andinasoft.countries'),
        ),
    ]
