# Generated by Django 3.2.16 on 2023-08-16 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0061_auto_20230816_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='sagrilaft_info',
            fields=[
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='andinasoft.clientes')),
                ('empresa_labora', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo_actual', models.CharField(blank=True, max_length=255, null=True)),
                ('origen_ingresos', models.CharField(max_length=255)),
                ('declara_renta', models.BooleanField(blank=True, null=True)),
                ('tiene_rut', models.BooleanField(blank=True, null=True)),
                ('preguntas_complementarias', models.CharField(blank=True, max_length=9999, null=True)),
                ('es_peps', models.BooleanField(blank=True, null=True)),
                ('peps_desde', models.DateField(blank=True, null=True)),
                ('peps_hasta', models.DateField(blank=True, null=True)),
                ('peps_entidad', models.CharField(blank=True, max_length=255, null=True)),
                ('peps_cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('peps_familiar', models.BooleanField(blank=True, null=True)),
                ('peps_familiar_parentesco', models.CharField(blank=True, max_length=255, null=True)),
                ('peps_familiar_entidad', models.CharField(blank=True, max_length=255, null=True)),
                ('peps_familiar_cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('referencia_familiar', models.CharField(blank=True, max_length=999, null=True)),
                ('referencia_familiar_telefono', models.CharField(blank=True, max_length=999, null=True)),
                ('referencia_personal', models.CharField(blank=True, max_length=999, null=True)),
                ('referencia_personal_telefono', models.CharField(blank=True, max_length=999, null=True)),
                ('codigo_ciuu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='andinasoft.ciuu')),
            ],
        ),
    ]
