# Generated by Django 3.2.16 on 2023-08-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0062_sagrilaft_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sagrilaft_info',
            options={'verbose_name': 'Información sagrilaft cliente', 'verbose_name_plural': 'Información sagrilaft clientes'},
        ),
        migrations.AddField(
            model_name='clientes',
            name='cual_otro_ocupacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
