# Generated by Django 3.2.16 on 2024-07-10 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('andinasoft', '0063_auto_20230817_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentas_pagos',
            name='es_caja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuentas_pagos',
            name='es_conciliable',
            field=models.BooleanField(default=False),
        ),
    ]
