# Generated by Django 3.2.16 on 2024-07-16 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('andinasoft', '0065_auto_20240710_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentas_pagos',
            name='usuario_aprobador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_aprobador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cuentas_pagos',
            name='usuario_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_responsable', to=settings.AUTH_USER_MODEL),
        ),
    ]
