# Generated by Django 3.2.16 on 2024-07-22 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('andinasoft', '0066_auto_20240716_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='fractales_ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_fracciones', models.IntegerField()),
                ('valor_fraccion', models.FloatField()),
                ('valor_lista_fraccion', models.FloatField()),
                ('valor_venta', models.FloatField()),
            ],
            options={
                'db_table': 'fractales_ventas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='reestructuraciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cuotas_vencidas', models.IntegerField()),
                ('dias_mora', models.IntegerField()),
                ('int_cte_causado', models.IntegerField()),
                ('int_mora_causado', models.IntegerField()),
                ('capital_pendiente', models.IntegerField()),
                ('interes_a_reestructurar', models.IntegerField()),
                ('cuotas_dividir_interes', models.IntegerField(blank=True, null=True)),
                ('tipo_reestructuracion', models.CharField(choices=[('CI', 'CI'), ('FN', 'FN'), ('CI+FN', 'CI+FN')], max_length=100)),
                ('nuevo_dia_pago', models.IntegerField(blank=True, null=True)),
                ('mover_meses', models.IntegerField(blank=True, null=True)),
                ('valor_ajuste', models.FloatField(blank=True, null=True)),
                ('nueva_ci', models.CharField(blank=True, max_length=500, null=True)),
                ('nueva_fn', models.CharField(blank=True, max_length=500, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Aplicado', 'Aplicado')], max_length=255)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('fecha_aplica', models.DateField(blank=True, null=True)),
                ('usuario_aplica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_aplica', to=settings.AUTH_USER_MODEL)),
                ('usuario_aprueba', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_aprueba_reestr', to=settings.AUTH_USER_MODEL)),
                ('usuario_solicita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_solicita_reestr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
