# Generated by Django 3.2.16 on 2024-07-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0067_fractales_ventas_reestructuraciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentas_pagos',
            name='oficina',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
