# Generated by Django 3.2.16 on 2026-01-06 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('andinasoft', '0068_cuentas_pagos_oficina'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan_pagos_reestructuracion',
            fields=[
                ('idcta', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tipocta', models.CharField(blank=True, max_length=255, null=True)),
                ('nrocta', models.IntegerField(blank=True, null=True)),
                ('adj', models.CharField(blank=True, max_length=255, null=True)),
                ('capital', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('intcte', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cuota', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='reestructuraciones_otrosi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cuotas_vencidas', models.IntegerField()),
                ('dias_mora', models.IntegerField()),
                ('int_cte_causado', models.IntegerField()),
                ('int_mora_causado', models.IntegerField()),
                ('capital_pendiente', models.IntegerField()),
                ('interes_a_reestructurar', models.IntegerField()),
                ('cuotas_dividir_interes', models.IntegerField(blank=True, null=True)),
                ('tipo_reestructuracion', models.CharField(choices=[('Normal', 'Normal'), ('Especial', 'Especial'), ('Descuento', 'Descuento')], max_length=100)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Firmado', 'Firmado'), ('Aplicado', 'Aplicado')], max_length=255)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('fecha_aplica', models.DateField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('solicitud', models.FileField(upload_to='otrosi/solicitudes')),
                ('otrosi', models.FileField(blank=True, null=True, upload_to='otrosi/firmados')),
                ('adj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='andinasoft.adjudicacion')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='andinasoft.proyectos')),
                ('usuario_aplica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_aplica', to=settings.AUTH_USER_MODEL)),
                ('usuario_aprueba', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_aprueba_reestr', to=settings.AUTH_USER_MODEL)),
                ('usuario_solicita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_solicita_reestr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='reestructuraciones',
        ),
        migrations.AddField(
            model_name='plan_pagos_reestructuracion',
            name='reestructuracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andinasoft.reestructuraciones_otrosi'),
        ),
    ]
