# Generated by Django 3.2.16 on 2026-03-03 20:16

import andina.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0069_add_upload_movements_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatars',
            name='image',
            field=models.ImageField(storage=andina.storage_backends.LocalMediaStorage(), upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='logo',
            field=models.ImageField(storage=andina.storage_backends.LocalMediaStorage(), upload_to='logos_empresas'),
        ),
        migrations.AlterField(
            model_name='reestructuraciones_otrosi',
            name='otrosi',
            field=models.FileField(blank=True, null=True, storage=andina.storage_backends.LocalMediaStorage(), upload_to='otrosi/firmados'),
        ),
        migrations.AlterField(
            model_name='reestructuraciones_otrosi',
            name='solicitud',
            field=models.FileField(storage=andina.storage_backends.LocalMediaStorage(), upload_to='otrosi/solicitudes'),
        ),
    ]
