# Generated by Django 3.2.16 on 2026-08-10 16:57

import andina.storage_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('andinasoft', '0078_carteracheckpoint_carteracartaplantilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='alegra_gasto_max_sin_aprobador',
            field=models.BigIntegerField(blank=True, help_text='COP (entero): tope para registrar gastos Alegra sin aprobador. Vacío o 0 = obligatorio designar aprobador.', null=True),
        ),
        migrations.CreateModel(
            name='CarteraCartaEnvio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adj', models.CharField(db_index=True, max_length=64)),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Correo'), ('fisico', 'Fisico / mensajeria'), ('otro', 'Otro')], default='whatsapp', max_length=20)),
                ('fecha_envio', models.DateField()),
                ('soporte', models.FileField(storage=andina.storage_backends.LocalMediaStorage(), upload_to='cartera/cartas_soporte/%Y/%m/')),
                ('notas', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='andinasoft.carteracheckpoint')),
                ('proyecto', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='cartera_carta_envios', to='andinasoft.proyectos')),
                ('usuario', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='cartera_carta_envios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Envio carta cobro',
                'verbose_name_plural': 'Envios cartas cobro',
                'ordering': ['-fecha_envio', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='carteracartaenvio',
            index=models.Index(fields=['proyecto', 'adj'], name='andinasoft__proyect_49a7f0_idx'),
        ),
        migrations.AddIndex(
            model_name='carteracartaenvio',
            index=models.Index(fields=['checkpoint', 'adj'], name='andinasoft__checkpo_c1181a_idx'),
        ),
    ]
