# Generated by Django 3.2.16 on 2026-08-10 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('andinasoft', '0079_carteracartaenvio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteraCartaGeneracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adj', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generaciones', to='andinasoft.carteracheckpoint')),
                ('proyecto', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='cartera_carta_generaciones', to='andinasoft.proyectos')),
                ('usuario', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='cartera_carta_generaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generacion carta cobro',
                'verbose_name_plural': 'Generaciones cartas cobro',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='carteracartageneracion',
            index=models.Index(fields=['proyecto', 'adj'], name='andinasoft__proyect_015813_idx'),
        ),
        migrations.AddIndex(
            model_name='carteracartageneracion',
            index=models.Index(fields=['checkpoint', 'adj'], name='andinasoft__checkpo_0f327b_idx'),
        ),
    ]
