# Generated by Django 3.2.13 on 2022-07-21 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('andinasoft', '0056_alter_asesores_tipo_asesor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='recibos_internos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('fecha_pago', models.DateField(auto_now=True)),
                ('soporte', models.FileField(upload_to='soportes_recibos')),
                ('valor', models.IntegerField()),
                ('cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('condonacion', models.FloatField(default=0)),
                ('abono_capital', models.BooleanField(blank=True, null=True)),
                ('fecha_confirma', models.DateField(blank=True, null=True)),
                ('recibo_asociado', models.CharField(blank=True, max_length=255, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='andinasoft.proyectos')),
                ('usuario_confirma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_confirma', to=settings.AUTH_USER_MODEL)),
                ('usuario_solicita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_solicita', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recibo interno',
                'verbose_name_plural': 'Recibos internos',
            },
        ),
    ]
