# Generated by Django 3.2.13 on 2022-08-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibos_internos',
            name='oficina',
            field=models.CharField(choices=[('Monteria', 'Monteria'), ('Medellin', 'Medellin')], default='Medellin', max_length=255),
            preserve_default=False,
        ),
    ]
