# Generated by Django 3.2.13 on 2022-08-17 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_recibos_internos_oficina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibos_internos',
            name='oficina',
        ),
    ]
