# Generated by Django 3.2.13 on 2022-08-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_recibos_internos_oficina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibos_internos',
            name='fecha_pago',
            field=models.DateField(),
        ),
    ]
