# Generated by Django 3.2.16 on 2023-10-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_recibos_internos_fecha_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibos_internos',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
    ]
