# Generated by Django 3.2.16 on 2026-03-03 20:16

import andina.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_recibos_internos_motivo_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibos_internos',
            name='soporte',
            field=models.FileField(storage=andina.storage_backends.LocalMediaStorage(), upload_to='soportes_recibos'),
        ),
    ]
