"""
Django settings for andina project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from dotenv import load_dotenv

load_dotenv()
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&a1m8@oo^5m4(8*q392qwn77egn!m_fi30y-m-e+^hzjw5hwaq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
LIVE = True

ALLOWED_HOSTS = ['app.somosandina.co','localhost','127.0.0.1','.ngrok-free.app']

# Application definition

INSTALLED_APPS = [
    'material',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',
    'registration', 
    'crispy_forms',
    'tempus_dominus',
    'django_cron',
    'django_crontab',
    'mathfilters',
    'andinasoft',
    'buildingcontrol',
    'crm',
    'accounting',
    'finance',
    'api_auth',
    'mcp_server',
]

TEMPUS_DOMINUS_LOCALIZE=True
TEMPUS_DOMINUS_INCLUDE_ASSETS=True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'andina.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'andina.wsgi.application'

if LIVE:
    #HOST = 'db'
    HOST = '31.220.49.112'

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'developer_web',
            'USER': 'developer_admin',
            'PASSWORD': 'uGuQIm8jGHlOYqtI',
            'HOST': HOST,
            'PORT': '3306',
            'OPTIONS':{
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'"
            }
        },
        'Sandville Beach':{
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'developer_sandville',
            'USER': 'developer_admin',
            'PASSWORD': 'uGuQIm8jGHlOYqtI',
            'HOST': HOST,
            'PORT': '3306',
        'OPTIONS':{
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'"
        }},
        'Perla del Mar':{
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'developer_sandvilledelmar',
            'USER': 'developer_admin',
            'PASSWORD': 'uGuQIm8jGHlOYqtI',
            'HOST': HOST,
            'PORT': '3306',
            'OPTIONS':{
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'"
            }
        },
        'Sandville del Sol':{
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'developer_sandvilledelsol',
            'USER': 'developer_admin',
            'PASSWORD': 'uGuQIm8jGHlOYqtI',
            'HOST': HOST,
            'PORT': '3306',
        'OPTIONS':{
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'"
        }},
        'Vegas de Venecia':{
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'developer_venecia',
            'USER': 'developer_admin',
            'PASSWORD': 'uGuQIm8jGHlOYqtI',
            'HOST': HOST,
            'PORT': '3306',
        'OPTIONS':{
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'"
        }},
        'Tesoro Escondido':{
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'developer_tesoro_escondido',
            'USER': 'developer_admin',
            'PASSWORD': 'uGuQIm8jGHlOYqtI',
            'HOST': HOST,
            'PORT': '3306',
        'OPTIONS':{
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'"
        }},
        'Sotavento':{
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'developer_sotavento',
            'USER': 'developer_admin',
            'PASSWORD': 'uGuQIm8jGHlOYqtI',
            'HOST': HOST,
            'PORT': '3306',
        'OPTIONS':{
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'"
        }},
        'Carmelo Reservado':{
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'developer_carmeloreservado',
            'USER': 'developer_admin',
            'PASSWORD': 'uGuQIm8jGHlOYqtI',
            'HOST': HOST,
            'PORT': '3306',
        'OPTIONS':{
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'"
        }},
        'Fractal':{
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'developer_fractal',
            'USER': 'developer_admin',
            'PASSWORD': 'uGuQIm8jGHlOYqtI',
            'HOST': HOST,
            'PORT': '3306',
        'OPTIONS':{
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'"
        }},
        'Alttum':{
                'ENGINE': 'django.db.backends.mysql',
                'NAME': 'developer_alttum',
                'USER': 'developer_admin',
                'PASSWORD': 'uGuQIm8jGHlOYqtI',
                'HOST': HOST,
                'PORT': '3306',
                'OPTIONS':{
                    'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
                }
            },
        'Casas de Verano':{
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'developer_casasdeverano',
            'USER': 'developer_admin',
            'PASSWORD': 'uGuQIm8jGHlOYqtI',
            'HOST': HOST,
            'PORT': '3306',
        'OPTIONS':{
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'"
        }},
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'andinaso_web',
            'USER': 'andinaso_001',
            'PASSWORD': 'Andina2020$',
            'HOST': 'andinasoft.com.co',
            'PORT': '3306',
            'OPTIONS':{
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'"
            }
        },
        'Sandville Beach':{
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'andinaso_sandville',
            'USER': 'andinaso_001',
            'PASSWORD': 'Andina2020$',
            'HOST': 'andinasoft.com.co',
            'PORT': '3306',
        'OPTIONS':{
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'"
        }},
        'Perla del Mar':{
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'andinaso_sandvilledelmar',
            'USER': 'andinaso_001',
            'PASSWORD': 'Andina2020$',
            'HOST': 'andinasoft.com.co',
            'PORT': '3306',
            'OPTIONS':{
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'"
            }
        },
        'Sandville del Sol':{
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'andinaso_sandvilledelsol',
            'USER': 'andinaso_001',
            'PASSWORD': 'Andina2020$',
            'HOST': 'andinasoft.com.co',
            'PORT': '3306',
        'OPTIONS':{
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'"
        }},
        'Vegas de Venecia':{
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'andinaso_venecia',
            'USER': 'andinaso_001',
            'PASSWORD': 'Andina2020$',
            'HOST': 'andinasoft.com.co',
            'PORT': '3306',
        'OPTIONS':{
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'"
        }},
        'Tesoro Escondido':{
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'andinaso_tesoro_escondido',
            'USER': 'andinaso_001',
            'PASSWORD': 'Andina2020$',
            'HOST': 'andinasoft.com.co',
            'PORT': '3306',
        'OPTIONS':{
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'"
        }},
        'Sotavento':{
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'andinaso_sotavento',
            'USER': 'andinaso_001',
            'PASSWORD': 'Andina2020$',
            'HOST': 'andinasoft.com.co',
            'PORT': '3306',
        'OPTIONS':{
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'"
        }},
        'Carmelo Reservado':{
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'andinaso_carmeloreservado',
            'USER': 'andinaso_001',
            'PASSWORD': 'Andina2020$',
            'HOST': 'andinasoft.com.co',
            'PORT': '3306',
        'OPTIONS':{
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'"
        }},
    }



# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_L10N = True

USE_THOUSAND_SEPARATOR = True

USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static_files')

STATICFILES_DIRS=[os.path.join(BASE_DIR, 'static_pro','static'),]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "static_media")

CRON_CLASSES = [
    "andinasoft.cron_jobs.job_cartera",
]

CRONJOBS = [
    ('*/5 * * * *', 'andinasoft.cron_jobs.ejemplo_job'),
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.app.somosandina.co'
EMAIL_USE_TLS = False
EMAIL_PORT = 587
EMAIL_HOST_USER = 'noreply@app.somosandina.co'
EMAIL_HOST_PASSWORD = 'M@5(LsLCn7C{9!c9'
DEFAULT_FROM_EMAIL = 'noreply@app.somosandina.co'

LOGIN_REDIRECT_URL='/welcome'
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"
CRISPY_TEMPLATE_PACK = 'bootstrap4'

ACCOUNT_ACTIVATION_DAYS = 7
REGISTRATION_AUTO_LOGIN = True
SITE_ID=1

if LIVE:
    DIR_DOCS = MEDIA_ROOT+'/docs_andinasoft'
    DIR_EXPORT=MEDIA_ROOT+'/tmp/'
    DIR_DOWNLOADS='https://app.somosandina.co/media/tmp/'

else:
    DIR_DOCS=MEDIA_ROOT+'/'
    DIR_EXPORT=MEDIA_ROOT+'/'
    DIR_DOWNLOADS='/media/'

# N8N Webhooks Configuration
N8N_WEBHOOK_UPLOAD_MOVEMENTS = os.getenv(
    'N8N_WEBHOOK_UPLOAD_MOVEMENTS',
    'http://localhost:5678/webhook/upload-movements'
)
N8N_WEBHOOK_WOMPI_COUNT = os.getenv(
    'N8N_WEBHOOK_WOMPI_COUNT',
    'http://localhost:5678/webhook/wompi-count'
)
N8N_WEBHOOK_PLINK_COUNT = os.getenv(
    'N8N_WEBHOOK_PLINK_COUNT',
    'http://localhost:5678/webhook/plink-count'
)
