# Generated by Django 3.2.16 on 2026-04-28 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('andinasoft', '0072_empresas_alegra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlegraSyncBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('receipt', 'Recibos de caja'), ('commission', 'Comisiones'), ('expense', 'Egresos')], max_length=40)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('preview', 'Preview'), ('processing', 'Procesando'), ('done', 'Completado'), ('failed', 'Fallido'), ('partial', 'Parcial')], default='pending', max_length=20)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('total_documents', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='alegra_batches', to='andinasoft.empresas')),
                ('proyecto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alegra_batches', to='andinasoft.proyectos')),
            ],
            options={
                'verbose_name': 'Lote Alegra',
                'verbose_name_plural': 'Lotes Alegra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlegraMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_type', models.CharField(choices=[('bank_account', 'Cuenta bancaria'), ('category', 'Cuenta/categoria contable'), ('contact', 'Contacto'), ('cost_center', 'Centro de costo'), ('numeration', 'Numeracion'), ('retention', 'Retencion'), ('payment_method', 'Metodo de pago'), ('bill', 'Factura/documento proveedor')], max_length=40)),
                ('local_model', models.CharField(blank=True, default='', max_length=120)),
                ('local_pk', models.CharField(blank=True, default='', max_length=255)),
                ('local_code', models.CharField(blank=True, default='', max_length=255)),
                ('alegra_id', models.CharField(max_length=255)),
                ('alegra_payload', models.JSONField(blank=True, default=dict)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='alegra_mappings', to='andinasoft.empresas')),
                ('proyecto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alegra_mappings', to='andinasoft.proyectos')),
            ],
            options={
                'verbose_name': 'Mapeo Alegra',
                'verbose_name_plural': 'Mapeos Alegra',
            },
        ),
        migrations.CreateModel(
            name='AlegraDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=40)),
                ('alegra_operation', models.CharField(blank=True, default='', max_length=120)),
                ('transport', models.CharField(blank=True, default='', max_length=20)),
                ('source_model', models.CharField(max_length=120)),
                ('source_pk', models.CharField(max_length=255)),
                ('local_key', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('alegra_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('valid', 'Valido'), ('invalid', 'Invalido'), ('sent', 'Enviado'), ('failed', 'Fallido'), ('skipped', 'Omitido')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='alegra_integration.alegrasyncbatch')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='alegra_documents', to='andinasoft.empresas')),
                ('proyecto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alegra_documents', to='andinasoft.proyectos')),
            ],
            options={
                'verbose_name': 'Documento Alegra',
                'verbose_name_plural': 'Documentos Alegra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alegramapping',
            index=models.Index(fields=['empresa', 'proyecto', 'mapping_type', 'local_model', 'local_pk'], name='alegra_mapping_local_pk_idx'),
        ),
        migrations.AddIndex(
            model_name='alegramapping',
            index=models.Index(fields=['empresa', 'proyecto', 'mapping_type', 'local_code'], name='alegra_mapping_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='alegramapping',
            constraint=models.UniqueConstraint(fields=('empresa', 'proyecto', 'mapping_type', 'local_model', 'local_pk', 'local_code'), name='unique_alegra_mapping'),
        ),
        migrations.AddConstraint(
            model_name='alegradocument',
            constraint=models.UniqueConstraint(fields=('empresa', 'document_type', 'local_key'), name='unique_alegra_document_local_key'),
        ),
    ]
