# Generated by Django 4.x

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alegra_integration', '0004_alegrawebhookinboundlog'),
        ('accounting', '0080_fix_alegra_bill_deleted_mysql_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlegraBillGetLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alegra_bill_id', models.CharField(db_index=True, max_length=64)),
                ('fields', models.CharField(blank=True, default='', max_length=255, verbose_name='fields (query)')),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='', verbose_name='notas / error')),
                ('pdf_saved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'empresa',
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='alegra_bill_get_logs',
                        to='andinasoft.empresas',
                    ),
                ),
                (
                    'factura',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='alegra_bill_get_logs',
                        to='accounting.facturas',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Log GET /bills Alegra (debug)',
                'verbose_name_plural': 'Logs GET /bills Alegra (debug)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alegrabillgetlog',
            index=models.Index(fields=['empresa', 'created_at'], name='alegra_bill_get_emp_ct_idx'),
        ),
    ]
