# Generated by Django 3.0.5 on 2021-03-10 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('andinasoft', '0048_auto_20210222_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operaciones',
            fields=[
                ('id_operacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('asesores', models.ManyToManyField(to='andinasoft.asesores')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andinasoft.proyectos')),
            ],
        ),
        migrations.CreateModel(
            name='leads',
            fields=[
                ('id_lead', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=255, unique=True)),
                ('telefono', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('Casado(a)', 'Casado(a)'), ('Soltero(a)', 'Soltero(a)'), ('Otro', 'Otro')], max_length=255, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], max_length=255)),
                ('tipo', models.CharField(choices=[('Poco interesado/Poco adecuado', 'Poco interesado/Poco adecuado'), ('Muy interesado/Poco adecuado', 'Muy interesado/Poco adecuado'), ('Poco interesado/Muy adecuado', 'Poco interesado/Muy adecuado'), ('Muy interesado/Muy adecuado', 'Muy interesado/Muy adecuado')], max_length=255)),
                ('gestor_aseginado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gestor_asignado', to='andinasoft.asesores')),
                ('gestor_capta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gestor_capta', to='andinasoft.asesores')),
            ],
        ),
        migrations.CreateModel(
            name='historyline_lead',
            fields=[
                ('id_history', models.AutoField(primary_key=True, serialize=False)),
                ('observacion', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.leads')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='eventos',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_evento', models.DateField()),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Operaciones')),
                ('usuario_crea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='asistentes_evento',
            fields=[
                ('id_asistente', models.AutoField(primary_key=True, serialize=False)),
                ('estado_cliente', models.CharField(choices=[('Sin confirmar', 'Sin confirmar'), ('Confirmado', 'Confirmado'), ('Asistio', 'Asistio'), ('No Asistio', 'No Asistio')], max_length=255)),
                ('estado_evento', models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], max_length=255)),
                ('asistente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.leads')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.eventos')),
                ('usuario_asigna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_asigna', to=settings.AUTH_USER_MODEL)),
                ('usuario_cierra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_cierra', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
