# Generated by Django 3.0.5 on 2021-03-15 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='operador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leads',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Asistio', 'Asistio'), ('Archivado', 'Archivado')], max_length=255),
        ),
        migrations.AlterField(
            model_name='leads',
            name='telefono',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
