# Generated by Django 3.0.5 on 2021-03-24 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0002_auto_20210315_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operador', to=settings.AUTH_USER_MODEL),
        ),
    ]
