# Generated by Django 3.0.5 on 2021-03-24 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0003_auto_20210323_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='ciudad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='fecha_capta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='asistentes_evento',
            unique_together={('evento', 'asistente')},
        ),
    ]
