# Generated by Django 3.0.5 on 2021-03-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20210324_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistentes_evento',
            name='estado_evento',
        ),
        migrations.AddField(
            model_name='eventos',
            name='estado_evento',
            field=models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=255),
            preserve_default=False,
        ),
    ]
