# Generated by Django 3.0.5 on 2021-03-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20210325_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='hora_evento',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='eventos',
            unique_together={('operacion', 'fecha_evento', 'hora_evento')},
        ),
    ]
