# Generated by Django 3.0.5 on 2021-03-26 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0006_auto_20210325_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='usuario_cierra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_cierra', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asistentes_evento',
            name='estado_cliente',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Asistio', 'Asistio'), ('No Asistio', 'No Asistio')], max_length=255),
        ),
    ]
