# Generated by Django 3.0.5 on 2021-04-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20210326_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('Casado(a)', 'Casado(a)'), ('Soltero(a)', 'Soltero(a)'), ('Viudo(a)', 'Viudo(a)'), ('Separado(a)', 'Separado(a)'), ('Otro', 'Otro')], max_length=255, null=True),
        ),
    ]
