# Generated by Django 3.0.5 on 2021-04-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20210406_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistentes_evento',
            name='cupos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
