# Generated by Django 3.0.5 on 2021-04-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_asistentes_evento_cupos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('En evento', 'En evento'), ('Asistio', 'Asistio'), ('Archivado', 'Archivado')], max_length=255),
        ),
    ]
