# Generated by Django 3.0.5 on 2021-04-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20210430_1345'),
    ]

    operations = [
        
    ]
