# Generated by Django 3.0.5 on 2021-05-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_remove_asistentes_evento_usuario_cierra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistentes_evento',
            name='usuario_cierra',
        ),
    ]
