# Generated by Django 3.0.5 on 2021-09-07 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('andinasoft', '0054_auto_20210724_1118'),
        ('crm', '0012_remove_asistentes_evento_usuario_cierra'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario_gestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asesor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='andinasoft.asesores')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario gestor',
                'verbose_name_plural': 'Usuarios gestores',
            },
        ),
    ]
