# Generated by Django 3.0.5 on 2021-09-08 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0013_usuario_gestor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventos',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='operaciones',
            options={'verbose_name': 'Operacion', 'verbose_name_plural': 'Operaciones'},
        ),
        migrations.AddField(
            model_name='operaciones',
            name='lider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
