# Generated by Django 3.2.16 on 2026-10-08 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatwootPanelToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='chatwoot_panel_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conexión del panel de Chatwoot',
                'verbose_name_plural': 'Conexiones del panel de Chatwoot',
                'ordering': ('-created_at',),
                'permissions': (('usar_panel_chatwoot', 'Puede usar el panel de Chatwoot'),),
            },
        ),
        migrations.CreateModel(
            name='ChatwootPanelAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(db_index=True, max_length=40)),
                ('proyecto', models.CharField(blank=True, default='', max_length=60)),
                ('adj', models.CharField(blank=True, default='', max_length=30)),
                ('chatwoot_account_id', models.CharField(blank=True, default='', max_length=20)),
                ('chatwoot_contact_id', models.CharField(blank=True, default='', max_length=20)),
                ('chatwoot_conversation_id', models.CharField(blank=True, default='', max_length=20)),
                ('detalle', models.CharField(blank=True, default='', max_length=500)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatwoot_panel.chatwootpaneltoken')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría del panel de Chatwoot',
                'verbose_name_plural': 'Auditoría del panel de Chatwoot',
                'ordering': ('-created_at',),
            },
        ),
    ]
