# Generated by Django 3.2.16 on 2026-10-08 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatwoot_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatwootContactLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatwoot_account_id', models.CharField(max_length=20)),
                ('chatwoot_contact_id', models.CharField(max_length=20)),
                ('cliente_id', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vínculo contacto Chatwoot ↔ cliente',
                'verbose_name_plural': 'Vínculos contacto Chatwoot ↔ cliente',
            },
        ),
        migrations.AddConstraint(
            model_name='chatwootcontactlink',
            constraint=models.UniqueConstraint(fields=('chatwoot_account_id', 'chatwoot_contact_id'), name='chatwoot_link_unico'),
        ),
    ]
