# Generated by Django 3.2.16 on 2026-10-08 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatwoot_panel', '0002_chatwootcontactlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatwootSeguimientoRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('proyecto', models.CharField(max_length=60)),
                ('adj', models.CharField(max_length=30)),
                ('seguimiento_id', models.IntegerField(blank=True, null=True)),
                ('chatwoot_account_id', models.CharField(blank=True, default='', max_length=20)),
                ('chatwoot_conversation_id', models.CharField(blank=True, default='', max_length=20)),
                ('nota_privada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento desde Chatwoot',
                'verbose_name_plural': 'Seguimientos desde Chatwoot',
            },
        ),
        migrations.AddIndex(
            model_name='chatwootseguimientoref',
            index=models.Index(fields=['proyecto', 'adj'], name='chatwoot_pa_proyect_93a5ea_idx'),
        ),
    ]
