# Generated by Django 3.0.5 on 2021-05-12 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('andinasoft', '0052_auto_20210512_1112'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='conciliaciones',
            fields=[
                ('id_concilacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('fecha_crea', models.DateField()),
                ('cuenta_asociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andinasoft.cuentas_pagos')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andinasoft.empresas')),
                ('usuario_crea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conciliacion',
                'verbose_name_plural': 'Conciliaciones',
            },
        ),
        migrations.CreateModel(
            name='planilla_movimiento',
            fields=[
                ('id_mvto', models.AutoField(primary_key=True, serialize=False)),
                ('año', models.IntegerField()),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='andinasoft.cuentas_pagos')),
                ('usuario_cierra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='egresos_banco',
            fields=[
                ('id_mvto', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('referencia', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado', models.CharField(choices=[('CONCILIADO', 'CONCILIADO'), ('SIN CONCILIAR', 'SIN CONCILIAR')], default='SIN CONCILIAR', max_length=255)),
                ('conciliacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.conciliaciones')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='andinasoft.cuentas_pagos')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andinasoft.empresas')),
            ],
            options={
                'verbose_name': 'Egreso banco',
                'verbose_name_plural': 'Egresos banco',
            },
        ),
        migrations.CreateModel(
            name='egresos_contable',
            fields=[
                ('id_mvto', models.AutoField(primary_key=True, serialize=False)),
                ('comprobante', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado', models.CharField(choices=[('CONCILIADO', 'CONCILIADO'), ('SIN CONCILIAR', 'SIN CONCILIAR')], default='SIN CONCILIAR', max_length=255)),
                ('tipo', models.CharField(blank=True, choices=[('PAGO', 'PAGO'), ('TRANSFERENCIA', 'TRANSFERENCIA'), ('CONSIGNACION', 'CONSIGNACION')], max_length=255, null=True)),
                ('conciliacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.conciliaciones')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='andinasoft.cuentas_pagos')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andinasoft.empresas')),
                ('pago_asociado', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='andinasoft.Pagos')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='andinasoft.proyectos')),
            ],
            options={
                'verbose_name': 'Egreso contable',
                'verbose_name_plural': 'Egresos contables',
                'unique_together': {('cuenta', 'comprobante')},
            },
        ),
    ]
