# Generated by Django 3.0.5 on 2021-05-12 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0052_auto_20210512_1112'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresos_contable',
            name='pago_asociado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='andinasoft.Pagos'),
        ),
    ]
