# Generated by Django 3.0.5 on 2021-05-13 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20210512_1741'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='egresos_contable',
            unique_together=set(),
        ),
    ]
