# Generated by Django 3.0.5 on 2021-05-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20210513_1005'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='egresos_contable',
            constraint=models.UniqueConstraint(fields=('comprobante', 'cuenta'), name='unique_egreso'),
        ),
    ]
