# Generated by Django 3.0.5 on 2021-05-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20210513_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conciliaciones',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='egresos_banco',
            name='referencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
