# Generated by Django 3.0.5 on 2021-05-26 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('andinasoft', '0053_cuentas_pagos_nit_empresa'),
        ('accounting', '0005_auto_20210518_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('nroradicado', models.AutoField(db_column='NroRadicado', primary_key=True, serialize=False)),
                ('fecharadicado', models.DateField(db_column='FechaRadica')),
                ('nrofactura', models.CharField(blank=True, db_column='NroFactura', max_length=255, null=True)),
                ('fechafactura', models.DateField(blank=True, db_column='FechaFactura', null=True)),
                ('idtercero', models.CharField(blank=True, db_column='idTercero', max_length=255, null=True)),
                ('nombretercero', models.CharField(blank=True, db_column='NombreTercero', max_length=255, null=True)),
                ('valor', models.IntegerField(blank=True, db_column='Valor', null=True)),
                ('pago_neto', models.IntegerField(blank=True, db_column='PagoNeto', null=True)),
                ('fechavenc', models.DateField(blank=True, db_column='FechaVenc', null=True)),
                ('nrocausa', models.CharField(blank=True, db_column='NroCausa', max_length=255, null=True)),
                ('fechacausa', models.DateField(blank=True, db_column='FechaCausa', null=True)),
                ('origen', models.CharField(choices=[('Radicado', 'Radicado'), ('Proyectos', 'Proyectos'), ('Interno', 'Interno'), ('Anticipos', 'Anticipos')], db_column='Origen', default='Radicado', max_length=255)),
                ('oficina', models.CharField(blank=True, choices=[('MONTERIA', 'MONTERIA'), ('MEDELLIN', 'MEDELLIN')], db_column='Oficina', max_length=255, null=True)),
                ('soporte_radicado', models.ImageField(blank=True, null=True, upload_to='Facturas/Soportes de pago')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andinasoft.empresas')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('idpago', models.AutoField(db_column='IdPago', primary_key=True, serialize=False)),
                ('valor', models.IntegerField(blank=True, db_column='Valorpago', null=True)),
                ('fechapago', models.DateField(blank=True, db_column='Fechapago', null=True)),
                ('formapago', models.CharField(blank=True, db_column='FormaPago', max_length=255, null=True)),
                ('soporte_pago', models.ImageField(blank=True, null=True, upload_to='Facturas/Soportes de pago')),
                ('cuentapago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='andinasoft.cuentas_pagos')),
                ('empresapago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='andinasoft.empresas')),
                ('nroradicado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.Facturas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='history_facturas',
            fields=[
                ('idmvto', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(choices=[('Recepcion', 'Recepcion'), ('Contabilidad', 'Contabilidad'), ('Tesoreria', 'Tesoreria'), ('Solicitante', 'Solicitante')], max_length=255)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Facturas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial factura',
                'verbose_name_plural': 'Historial Facturas',
            },
        ),
        migrations.AlterField(
            model_name='egresos_contable',
            name='pago_asociado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.Pagos'),
        ),
        migrations.AddConstraint(
            model_name='facturas',
            constraint=models.UniqueConstraint(fields=('idtercero', 'nrofactura'), name='unique_factura'),
        ),
    ]
