# Generated by Django 3.0.5 on 2021-05-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20210525_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='fecharadicado',
            field=models.DateField(auto_created=True, db_column='FechaRadica'),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='soporte_radicado',
            field=models.FileField(blank=True, null=True, upload_to='Facturas/Soportes de pago'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='soporte_pago',
            field=models.FileField(blank=True, null=True, upload_to='Facturas/Soportes de pago'),
        ),
    ]
