# Generated by Django 3.0.5 on 2021-05-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20210526_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='fecharadicado',
            field=models.DateField(auto_now=True, db_column='FechaRadica'),
        ),
    ]
