# Generated by Django 3.0.5 on 2021-05-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_auto_20210526_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_facturas',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
