# Generated by Django 3.0.5 on 2021-05-26 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_auto_20210526_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='egreso_rel',
            field=models.OneToOneField(default=126, on_delete=django.db.models.deletion.PROTECT, to='accounting.egresos_contable'),
            preserve_default=False,
        ),
    ]
