# Generated by Django 3.0.5 on 2021-07-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_auto_20210526_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagos',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AddField(
            model_name='pagos',
            name='fecha_pago',
            field=models.DateField(default='2021-05-21'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagos',
            name='fecha_registro',
            field=models.DateTimeField(auto_created=True, default='2021-07-19'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='egresos_contable',
            name='tipo',
            field=models.CharField(blank=True, choices=[('PAGO', 'PAGO'), ('TRANSFERENCIA', 'TRANSFERENCIA'), ('ANTICIPO', 'ANTICIPO'), ('CONSIGNACION', 'CONSIGNACION'), ('INTEREMPRESAS', 'INTEREMPRESAS')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='valor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
