# Generated by Django 3.0.5 on 2021-07-20 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0053_cuentas_pagos_nit_empresa'),
        ('accounting', '0011_auto_20210719_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='cuenta',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_pago', to='andinasoft.cuentas_pagos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagos',
            name='empresa',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, related_name='empresa_pago', to='andinasoft.empresas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagos',
            name='fecha_registro',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
