# Generated by Django 3.0.5 on 2021-07-21 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0053_cuentas_pagos_nit_empresa'),
        ('accounting', '0012_auto_20210720_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='info_interfaces',
            fields=[
                ('id_doc', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo_doc', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_doc', models.CharField(blank=True, max_length=255, null=True)),
                ('cuenta_debito_1', models.CharField(blank=True, max_length=255, null=True)),
                ('cuenta_debito_2', models.CharField(blank=True, max_length=255, null=True)),
                ('cuenta_debito_3', models.CharField(blank=True, max_length=255, null=True)),
                ('cuenta_credito_1', models.CharField(blank=True, max_length=255, null=True)),
                ('cuenta_credito_2', models.CharField(blank=True, max_length=255, null=True)),
                ('cuenta_credito_3', models.CharField(blank=True, max_length=255, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andinasoft.empresas')),
            ],
        ),
    ]
