# Generated by Django 3.0.5 on 2021-07-21 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_auto_20210721_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info_interfaces',
            options={'verbose_name': 'Interfaz', 'verbose_name_plural': 'Interfaces'},
        ),
        migrations.RemoveField(
            model_name='egresos_contable',
            name='pago_asociado',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='cuentapago',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='egreso_rel',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='empresapago',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='fechapago',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='formapago',
        ),
    ]
