# Generated by Django 3.0.5 on 2021-07-22 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_auto_20210721_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='cuenta_por_pagar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.info_interfaces'),
        ),
    ]
