# Generated by Django 3.0.5 on 2021-07-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_facturas_cuenta_por_pagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='secuencia_cxp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
