# Generated by Django 3.0.5 on 2021-07-24 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0054_auto_20210724_1118'),
        ('accounting', '0016_facturas_secuencia_cxp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_causa', to='andinasoft.empresas'),
        ),
    ]
