# Generated by Django 3.0.5 on 2021-07-26 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0054_auto_20210724_1118'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0017_auto_20210724_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anticipos',
            fields=[
                ('id_ant', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('id_tercero', models.CharField(max_length=255)),
                ('nombre_tercero', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_pago', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('soporte_pago', models.FileField(blank=True, null=True, upload_to='Anticipos/Soportes de pago')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_anticipo', to='andinasoft.cuentas_pagos')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresa_anticipo', to='andinasoft.empresas')),
                ('tipo_anticipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_anticipo', to='accounting.info_interfaces')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anticipo',
                'verbose_name_plural': 'Anticipos',
            },
        ),
    ]
