# Generated by Django 3.0.5 on 2021-07-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_anticipos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info_interfaces',
            name='numero_doc',
        ),
        migrations.AddField(
            model_name='facturas',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
