# Generated by Django 3.0.5 on 2021-08-10 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0054_auto_20210724_1118'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0019_auto_20210727_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='origen',
            field=models.CharField(choices=[('Radicado', 'Radicado'), ('Proyectos', 'Proyectos'), ('Comisiones', 'Comisiones'), ('GTT', 'GTT'), ('Otros', 'Otros')], db_column='Origen', default='Radicado', max_length=255),
        ),
        migrations.CreateModel(
            name='otros_ingresos',
            fields=[
                ('id_ingreso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ing', models.DateField()),
                ('id_tercero', models.CharField(max_length=255)),
                ('nombre_tercero', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('valor', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('soporte', models.FileField(blank=True, null=True, upload_to='Otros Ingresos')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='andinasoft.cuentas_pagos')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='andinasoft.empresas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Otros ingresos',
            },
        ),
    ]
