# Generated by Django 3.0.5 on 2021-08-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_auto_20210809_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='otros_ingresos',
            name='oficina',
            field=models.CharField(choices=[('MEDELLIN', 'MEDELLIN'), ('MONTERIA', 'MONTERIA')], default='MEDELLIN', max_length=255),
            preserve_default=False,
        ),
    ]
