# Generated by Django 3.0.5 on 2021-08-12 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0054_auto_20210724_1118'),
        ('accounting', '0021_otros_ingresos_oficina'),
    ]

    operations = [
        migrations.CreateModel(
            name='transferencias_companias',
            fields=[
                ('id_transf', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('valor', models.IntegerField()),
                ('cuenta_entra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_entra', to='andinasoft.cuentas_pagos')),
                ('cuenta_sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_sale', to='andinasoft.cuentas_pagos')),
                ('empresa_entra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresa_entra', to='andinasoft.empresas')),
                ('empresa_sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresa_sale', to='andinasoft.empresas')),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
            },
        ),
    ]
