# Generated by Django 3.0.5 on 2021-08-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_transferencias_companias'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencias_companias',
            name='oficina',
            field=models.CharField(choices=[('MEDELLIN', 'MEDELLIN'), ('MONTERIA', 'MONTERIA')], default='MONTERIA', max_length=255),
            preserve_default=False,
        ),
    ]
