# Generated by Django 3.0.5 on 2021-08-13 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_transferencias_companias_oficina'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencias_companias',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
