# Generated by Django 3.0.5 on 2021-08-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_transferencias_companias_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='anticipos',
            name='oficina',
            field=models.CharField(choices=[('MEDELLIN', 'MEDELLIN'), ('MONTERIA', 'MONTERIA')], default='MEDELLIN', max_length=255),
            preserve_default=False,
        ),
    ]
