# Generated by Django 3.0.5 on 2021-08-18 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0054_auto_20210724_1118'),
        ('accounting', '0025_anticipos_oficina'),
    ]

    operations = [
        migrations.CreateModel(
            name='docs_tipos_oficinas',
            fields=[
                ('id_rel', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
                ('oficina', models.CharField(choices=[('MEDELLIN', 'MEDELLIN'), ('MONTERIA', 'MONTERIA')], max_length=255)),
                ('documento', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Documento rel',
                'verbose_name_plural': 'Tipos docs conceptos',
            },
        ),
        migrations.CreateModel(
            name='docs_cuentas_oficinas',
            fields=[
                ('id_rel', models.AutoField(primary_key=True, serialize=False)),
                ('oficina', models.CharField(choices=[('MEDELLIN', 'MEDELLIN'), ('MONTERIA', 'MONTERIA')], max_length=255)),
                ('documento', models.CharField(max_length=255)),
                ('cuenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='andinasoft.cuentas_pagos')),
            ],
            options={
                'verbose_name': 'Documento rel',
                'verbose_name_plural': 'Tipos docs cuentas',
            },
        ),
    ]
