# Generated by Django 3.0.5 on 2021-08-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0054_auto_20210724_1118'),
        ('accounting', '0026_docs_cuentas_oficinas_docs_tipos_oficinas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docs_cuentas_oficinas',
            name='cuenta',
        ),
        migrations.AddField(
            model_name='docs_cuentas_oficinas',
            name='cuenta',
            field=models.ManyToManyField(to='andinasoft.cuentas_pagos'),
        ),
    ]
