# Generated by Django 3.0.5 on 2021-08-18 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0054_auto_20210724_1118'),
        ('accounting', '0027_auto_20210817_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docs_cuentas_oficinas',
            name='oficina',
        ),
        migrations.AddField(
            model_name='docs_cuentas_oficinas',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='andinasoft.empresas'),
            preserve_default=False,
        ),
    ]
