# Generated by Django 3.0.5 on 2021-08-18 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0054_auto_20210724_1118'),
        ('accounting', '0028_auto_20210817_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs_tipos_oficinas',
            name='empresa',
            field=models.ForeignKey(default=900993044, on_delete=django.db.models.deletion.PROTECT, to='andinasoft.empresas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facturas',
            name='fecharadicado',
            field=models.DateField(auto_now_add=True, db_column='FechaRadica'),
        ),
    ]
