# Generated by Django 3.0.5 on 2021-08-23 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0054_auto_20210724_1118'),
        ('accounting', '0029_auto_20210818_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuentas_intercompanias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CXP', 'CXP'), ('CXC', 'CXC')], max_length=255)),
                ('tipo_documento', models.CharField(max_length=5)),
                ('empresa_desde', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresa_desde', to='andinasoft.empresas')),
                ('empresa_hacia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresa_hacia', to='andinasoft.empresas')),
            ],
            options={
                'verbose_name': 'Cuenta intercompañia',
                'verbose_name_plural': 'Cuentas intercompañia',
            },
        ),
    ]
