# Generated by Django 3.0.5 on 2021-08-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_cuentas_intercompanias'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentas_intercompanias',
            name='cuenta',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
