# Generated by Django 3.0.5 on 2021-08-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_cuentas_intercompanias_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas_intercompanias',
            name='cuenta',
            field=models.BigIntegerField(),
        ),
    ]
