# Generated by Django 3.0.5 on 2021-08-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0054_auto_20210724_1118'),
        ('accounting', '0032_auto_20210823_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuentas_intercompanias',
            old_name='cuenta',
            new_name='cuenta_por_cobrar',
        ),
        migrations.AddField(
            model_name='cuentas_intercompanias',
            name='cuenta_por_pagar',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cuentas_intercompanias',
            unique_together={('empresa_desde', 'empresa_hacia')},
        ),
        migrations.RemoveField(
            model_name='cuentas_intercompanias',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='cuentas_intercompanias',
            name='tipo_documento',
        ),
    ]
