# Generated by Django 3.0.5 on 2021-08-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_auto_20210824_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentas_intercompanias',
            name='documento',
            field=models.CharField(default='N', max_length=5),
            preserve_default=False,
        ),
    ]
