# Generated by Django 3.0.5 on 2021-08-25 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0054_auto_20210724_1118'),
        ('accounting', '0034_cuentas_intercompanias_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='comision_relacionada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comisiones', models.ManyToManyField(to='andinasoft.Pagocomision')),
                ('radicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Facturas')),
            ],
        ),
        migrations.CreateModel(
            name='gtt_relacionado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='andinasoft.Gtt')),
                ('radicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Facturas')),
            ],
            options={
                'unique_together': {('radicado', 'gtt')},
            },
        ),
    ]
