# Generated by Django 3.0.5 on 2021-08-25 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0035_comision_relacionada_gtt_relacionado'),
    ]

    operations = [
        migrations.CreateModel(
            name='pago_detallado_relacionado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tercero', models.CharField(max_length=255)),
                ('nombre_tercero', models.CharField(max_length=255)),
                ('vencimiento', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Pagos')),
            ],
            options={
                'verbose_name': 'Pago relacionado',
                'verbose_name_plural': 'Pagos relacionados',
                'unique_together': {('pago', 'id_tercero')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='gtt_relacionado',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='gtt_relacionado',
            name='gtt',
        ),
        migrations.RemoveField(
            model_name='gtt_relacionado',
            name='radicado',
        ),
        migrations.DeleteModel(
            name='comision_relacionada',
        ),
        migrations.DeleteModel(
            name='gtt_relacionado',
        ),
    ]
