# Generated by Django 3.0.5 on 2021-08-31 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0054_auto_20210724_1118'),
        ('accounting', '0036_auto_20210825_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='saldos_cuentas_tesoreria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('saldo_inicial', models.FloatField()),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='andinasoft.cuentas_pagos')),
            ],
            options={
                'verbose_name': 'Saldo inicio dia',
                'verbose_name_plural': 'Saldos inicio dia',
                'unique_together': {('cuenta', 'fecha')},
            },
        ),
    ]
