# Generated by Django 3.0.5 on 2021-08-31 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0037_saldos_cuentas_tesoreria'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldos_cuentas_tesoreria',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
