# Generated by Django 3.0.5 on 2021-08-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0038_saldos_cuentas_tesoreria_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldos_cuentas_tesoreria',
            name='forma',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
