# Generated by Django 3.0.5 on 2021-12-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0039_saldos_cuentas_tesoreria_forma'),
    ]

    operations = [
        migrations.CreateModel(
            name='distribucion_centros_costos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=255)),
                ('centro', models.CharField(max_length=255)),
                ('subcentro', models.CharField(blank=True, max_length=255, null=True)),
                ('porcentaje', models.FloatField()),
            ],
            options={
                'verbose_name': 'Distribucion centro de costo',
                'verbose_name_plural': 'Distribucion centros de costos',
            },
        ),
    ]
