# Generated by Django 3.2.16 on 2022-12-06 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0040_distribucion_centros_costos'),
    ]

    operations = [
        migrations.CreateModel(
            name='info_facturas',
            fields=[
                ('radicado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombretercero', models.CharField(max_length=255)),
                ('fecharadicado', models.DateField()),
                ('fechafactura', models.DateField()),
                ('valor', models.IntegerField()),
                ('pagoneto', models.IntegerField()),
                ('empresa', models.CharField(max_length=255)),
                ('causacion', models.CharField(max_length=255)),
                ('origen', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('pagos', models.DecimalField(decimal_places=2, max_digits=32)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=32)),
                ('oficina', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'info_facturas',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='anticipos',
            options={'verbose_name': 'Pago de anticipo', 'verbose_name_plural': 'Pago de anticipos'},
        ),
        migrations.CreateModel(
            name='solicitud_anticipos',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('valor', models.IntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'aprobado'), ('pagado', 'Pagado'), ('legalizado', 'Legalizado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=255)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='andinasoft.empresas')),
                ('pago_anticipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.anticipos')),
                ('usuario_aprueba', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_ant_aprueba', to=settings.AUTH_USER_MODEL)),
                ('usuario_solicita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_ant_solicita', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de anticipo',
                'verbose_name_plural': 'Solicitudes de anticipos',
            },
        ),
        migrations.CreateModel(
            name='reintegros_anticipos',
            fields=[
                ('id_reintegro', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('tipo', models.CharField(choices=[('D', 'A la empresa'), ('C', 'Al empleado')], max_length=255)),
                ('id_anticipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.solicitud_anticipos')),
            ],
            options={
                'verbose_name': 'Reintegro de anticipo',
                'verbose_name_plural': 'Reintegros de anticipos',
            },
        ),
        migrations.CreateModel(
            name='legalizacion_anticipos',
            fields=[
                ('id_legalizacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_gasto', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('valor', models.IntegerField()),
                ('soporte', models.FileField(upload_to='legalizaciones_anticipos')),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_legalizacion', models.DateField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('anticipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.solicitud_anticipos')),
                ('usuario_aprueba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_leg_aprueba', to=settings.AUTH_USER_MODEL)),
                ('usuario_carga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_leg_carga', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legalizacion de anticipo',
                'verbose_name_plural': 'Legalizaciones de anticipos',
            },
        ),
    ]
