# Generated by Django 3.2.16 on 2022-12-07 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0041_auto_20221206_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_anticipos',
            name='usuario_aprueba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_ant_aprueba', to=settings.AUTH_USER_MODEL),
        ),
    ]
