# Generated by Django 3.2.16 on 2023-01-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0042_alter_solicitud_anticipos_usuario_aprueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_anticipos',
            name='oficina',
            field=models.CharField(choices=[('MEDELLIN', 'MEDELLIN'), ('MONTERIA', 'MONTERIA')], default='MEDELLIN', max_length=255),
            preserve_default=False,
        ),
    ]
