# Generated by Django 3.2.16 on 2023-01-18 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0058_auto_20221206_1627'),
        ('accounting', '0043_solicitud_anticipos_oficina'),
    ]

    operations = [
        migrations.CreateModel(
            name='conceptos_legalizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cuenta_contable', models.CharField(help_text='Incluir los 10 digitos de la cuenta en SIIGO', max_length=255)),
                ('naturaleza_cuenta', models.CharField(choices=[('D', 'Debito'), ('C', 'Credito')], max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='andinasoft.empresas')),
            ],
            options={
                'verbose_name': 'Concepto legalizacion',
                'verbose_name_plural': 'Conceptos legalizacion',
            },
        ),
    ]
