# Generated by Django 3.2.16 on 2023-01-19 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0044_conceptos_legalizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_anticipos',
            name='quien_aprueba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_who_approve', to=settings.AUTH_USER_MODEL),
        ),
    ]
