# Generated by Django 3.2.16 on 2023-01-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0045_solicitud_anticipos_quien_aprueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalizacion_anticipos',
            name='nit_tercero',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalizacion_anticipos',
            name='nombre_tercero',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
