# Generated by Django 3.2.16 on 2023-01-19 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0046_auto_20230119_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalizacion_anticipos',
            name='concepto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounting.conceptos_legalizacion'),
            preserve_default=False,
        ),
    ]
