# Generated by Django 3.2.16 on 2023-02-15 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0048_auto_20230201_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_city', models.CharField(max_length=255)),
                ('city_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id_country', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_state', models.CharField(max_length=255)),
                ('state_name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.countries')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('idTercero', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('document_type', models.CharField(blank=True, choices=[('13', 'Cédula de ciudadanía'), ('31', 'NIT'), ('22', 'Cédula de extranjería'), ('42', 'Documento de identificación extranjero'), ('50', 'NIT de otro país'), ('R-00-PN', 'No obligado a registrarse en el RUT PN'), ('91', 'NUIP'), ('41', 'Pasaporte'), ('47', 'Permiso especial de permanencia PEP'), ('11', 'Registro civil'), ('43', 'Sin identificación del exterior o para uso definido por la DIAN'), ('21', 'Tarjeta de extranjería'), ('12', 'Tarjeta de identidad')], max_length=255, null=True)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('responsabilidad_fiscal', models.CharField(blank=True, choices=[('R-99-PN', 'No Aplica - Otros*'), ('O-13', 'Gran contribuyente'), ('O-15', 'Autorretenedor'), ('O-23', 'Agente de retención IVA'), ('O-47', 'Régimen simple de tributación')], max_length=255, null=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('siigo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.cities')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.states')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.countries')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.AddField(
            model_name='cities',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.states'),
        ),
    ]
