# Generated by Django 3.2.16 on 2023-02-15 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0049_auto_20230215_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalizacion_anticipos',
            name='nit_tercero',
        ),
        migrations.RemoveField(
            model_name='legalizacion_anticipos',
            name='nombre_tercero',
        ),
        migrations.AddField(
            model_name='legalizacion_anticipos',
            name='tercero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounting.partners'),
            preserve_default=False,
        ),
    ]
