# Generated by Django 3.2.19 on 2023-06-08 16:52

import accounting.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0058_auto_20221206_1627'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0050_auto_20230215_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='archivo_contable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(max_length=255)),
                ('fecha_doc', models.DateField()),
                ('document', models.FileField(upload_to=accounting.models.upload_to)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='andinasoft.empresas')),
                ('user_carga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
