# Generated by Django 3.2.19 on 2023-06-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0058_auto_20221206_1627'),
        ('accounting', '0051_archivo_contable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivo_contable',
            options={'verbose_name': 'Archivo contable', 'verbose_name_plural': 'Archivo contable'},
        ),
        migrations.AddField(
            model_name='archivo_contable',
            name='consecutivo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='archivo_contable',
            unique_together={('empresa', 'tipo_doc', 'consecutivo')},
        ),
    ]
