# Generated by Django 3.2.19 on 2023-06-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0052_auto_20230608_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo_contable',
            name='ocr_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
