# Generated by Django 3.2.19 on 2023-06-29 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0059_cities_countries_states'),
        ('accounting', '0053_archivo_contable_ocr_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='andinasoft.cities'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='andinasoft.states'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='andinasoft.countries'),
        ),
        migrations.DeleteModel(
            name='Cities',
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
        migrations.DeleteModel(
            name='States',
        ),
    ]
