# Generated by Django 3.2.16 on 2023-11-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0054_auto_20230629_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptos_legalizacion',
            name='cuenta_contable',
        ),
        migrations.RemoveField(
            model_name='conceptos_legalizacion',
            name='empresa',
        ),
        migrations.AddField(
            model_name='conceptos_legalizacion',
            name='cuenta_andina',
            field=models.CharField(blank=True, help_text='Incluir los 10 digitos de la cuenta en SIIGO', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conceptos_legalizacion',
            name='cuenta_quadrata',
            field=models.CharField(blank=True, help_text='Incluir los 10 digitos de la cuenta en SIIGO', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conceptos_legalizacion',
            name='cuenta_status',
            field=models.CharField(blank=True, help_text='Incluir los 10 digitos de la cuenta en SIIGO', max_length=255, null=True),
        ),
    ]
