# Generated by Django 3.2.16 on 2023-11-22 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0055_auto_20231122_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='impuestos_legalizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('naturaleza_cuenta', models.CharField(choices=[('D', 'Debito'), ('C', 'Credito')], max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('cuenta_andina', models.CharField(blank=True, help_text='Incluir los 10 digitos de la cuenta en SIIGO', max_length=255, null=True)),
                ('cuenta_status', models.CharField(blank=True, help_text='Incluir los 10 digitos de la cuenta en SIIGO', max_length=255, null=True)),
                ('cuenta_quadrata', models.CharField(blank=True, help_text='Incluir los 10 digitos de la cuenta en SIIGO', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Impuesto legalizacion',
                'verbose_name_plural': 'Impuestos legalizacion',
            },
        ),
        migrations.AddField(
            model_name='legalizacion_anticipos',
            name='rte_asumida',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalizacion_anticipos',
            name='valor_iva',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalizacion_anticipos',
            name='valor_rte',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalizacion_anticipos',
            name='cuenta_iva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_iva', to='accounting.impuestos_legalizacion'),
        ),
        migrations.AddField(
            model_name='legalizacion_anticipos',
            name='cuenta_rte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_rte', to='accounting.impuestos_legalizacion'),
        ),
    ]
