# Generated by Django 3.2.16 on 2024-05-28 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0056_auto_20231122_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresos_banco',
            name='anticipo_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.anticipos'),
        ),
        migrations.AddField(
            model_name='egresos_banco',
            name='pago_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.pagos'),
        ),
        migrations.AddField(
            model_name='egresos_banco',
            name='transferencia_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.transferencias_companias'),
        ),
        migrations.AddField(
            model_name='transferencias_companias',
            name='soporte',
            field=models.FileField(blank=True, null=True, upload_to='Transferencias/Soportes de pago'),
        ),
    ]
