# Generated by Django 3.2.16 on 2024-05-28 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0057_auto_20240528_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='soporte_causacion',
            field=models.FileField(blank=True, null=True, upload_to='Facturas/Causacion'),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='soporte_radicado',
            field=models.FileField(blank=True, null=True, upload_to='Facturas/Facturas'),
        ),
    ]
