# Generated by Django 3.2.16 on 2024-05-29 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0058_auto_20240528_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='centro_costo',
            field=models.CharField(blank=True, choices=[('Administracion', 'Administracion'), ('Comercial', 'Comercial'), ('Proyectos', 'Proyectos'), ('Operacion', 'Operacion'), ('Integral', 'Integral'), ('Impuestos', 'Impuestos'), ('Tierras', 'Tierras')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facturas',
            name='proyecto_rel',
            field=models.CharField(blank=True, choices=[('Perla del Mar', 'Perla del Mar'), ('Caracola del Mar', 'Caracola del Mar'), ('Bugambilias', 'Bugambilias'), ('Vegas de Venecia', 'Vegas de Venecia'), ('Carmelo Reservado', 'Carmelo Reservado'), ('Fractal', 'Fractal'), ('Alttum Venecia', 'Alttum Caribe'), ('Integral', 'Integral')], max_length=255, null=True),
        ),
    ]
