# Generated by Django 3.2.16 on 2024-05-30 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0059_auto_20240529_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresos_contable',
            name='soporte_egreso',
            field=models.FileField(blank=True, null=True, upload_to='Facturas/Egresos contables'),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='centro_costo',
            field=models.CharField(blank=True, choices=[('Administracion', 'Administracion'), ('Comercial', 'Comercial'), ('Proyectos', 'Proyectos'), ('Operacion club', 'Operacion club'), ('Integral', 'Integral'), ('Impuestos', 'Impuestos'), ('Tierras', 'Tierras')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='proyecto_rel',
            field=models.CharField(blank=True, choices=[('Perla del Mar', 'Perla del Mar'), ('Caracola del Mar', 'Caracola del Mar'), ('Bugambilias', 'Bugambilias'), ('Vegas de Venecia', 'Vegas de Venecia'), ('Carmelo Reservado', 'Carmelo Reservado'), ('Fractal', 'Fractal'), ('Alttum Venecia', 'Alttum Venecia'), ('Alttum Caribe', 'Alttum Caribe'), ('Integral', 'Integral')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reintegros_anticipos',
            name='id_anticipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anticipo', to='accounting.solicitud_anticipos'),
        ),
    ]
