# Generated by Django 3.2.16 on 2024-05-31 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0060_auto_20240530_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferencias_companias',
            old_name='soporte',
            new_name='soporte_pago',
        ),
    ]
