# Generated by Django 3.2.16 on 2024-07-10 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0061_rename_soporte_transferencias_companias_soporte_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anticipos_hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('reservas', 'Reservas'), ('dia de sol', 'Día de sol')], max_length=255)),
                ('valor', models.FloatField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('id_siigo', models.CharField(blank=True, max_length=255, null=True)),
                ('vencimiento_siigo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'hotels_anticipos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_city', models.CharField(max_length=255)),
                ('city_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'controlpanel_cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idTercero', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('document_type', models.CharField(blank=True, choices=[('13', 'Cédula de ciudadanía'), ('31', 'NIT'), ('22', 'Cédula de extranjería'), ('42', 'Documento de identificación extranjero'), ('50', 'NIT de otro país'), ('R-00-PN', 'No obligado a registrarse en el RUT PN'), ('91', 'NUIP'), ('41', 'Pasaporte'), ('47', 'Permiso especial de permanencia PEP'), ('11', 'Registro civil'), ('43', 'Sin identificación del exterior o para uso definido por la DIAN'), ('21', 'Tarjeta de extranjería'), ('12', 'Tarjeta de identidad')], max_length=255, null=True)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_residencia', models.CharField(max_length=255)),
                ('direccion_oficina', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField()),
                ('ocupacion', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_hijos', models.IntegerField(blank=True, null=True)),
                ('nivel_educativo', models.CharField(blank=True, choices=[('Bachiller', 'Bachiller'), ('Tecnico', 'Tecnico'), ('Pregrado', 'Pregrado'), ('Postgrado', 'Postgrado'), ('Maestria', 'Maestria')], max_length=255, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_ingresos', models.CharField(blank=True, choices=[('MENOR A 3.5 MILLONES', 'MENOR A 3.5 MILLONES'), ('3.5 A 4.5 MILLONES', '3.5 A 4.5 MILLONES'), ('4.5 A 6.5 MILLONES', '4.5 A 6.5 MILLONES'), ('MAYOR A 6.5 MILLONES', 'MAYOR A 6.5 MILLONES')], max_length=255, null=True)),
                ('vehiculo', models.CharField(blank=True, choices=[('CARRO', 'CARRO'), ('MOTO', 'MOTO'), ('CARRO/MOTO', 'CARRO/MOTO'), ('NO', 'NO')], max_length=255, null=True)),
                ('vivienda', models.CharField(blank=True, choices=[('PROPIA', 'PROPIA'), ('FAMILIAR', 'FAMILIAR'), ('ARRENDADA', 'ARRENDADA')], max_length=255, null=True)),
                ('pasatiempos', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('siigo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_registro', models.CharField(blank=True, max_length=255, null=True)),
                ('geoloc_registro', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ventas_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consumos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('reserva', 'reserva'), ('dia de sol', 'dia de sol')], max_length=255)),
                ('valor', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('fecha_consumo', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'hotels_consumos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id_country', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'controlpanel_countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dias_de_sol',
            fields=[
                ('nro_dia_sol', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('pax', models.IntegerField()),
                ('childs', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], max_length=255)),
                ('pago_al_ingreso', models.CharField(default='0|None', max_length=255)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'hotels_dias_de_sol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facturas_hoteles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('id_siigo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hotels_facturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Forma_pago_alttum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, unique=True)),
                ('cuenta_banco', models.CharField(max_length=255)),
                ('cuenta_contable', models.CharField(max_length=255)),
                ('cuenta_andinasoft', models.IntegerField(blank=True, null=True)),
                ('id_siigo', models.CharField(blank=True, max_length=255, null=True)),
                ('caja_hotel', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ventas_forma_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255)),
                ('capacidad', models.IntegerField()),
            ],
            options={
                'db_table': 'hotels_habitaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hoteles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hoteles')),
                ('id_facturacion_siigo', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'hotels_hoteles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Impuestos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('id_siigo', models.IntegerField()),
                ('porcentaje', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'hotels_impuestos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagos_facturas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hotels_pagos_facturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('id_prod_siigo', models.CharField(max_length=255)),
                ('es_compuesto', models.BooleanField(default=False)),
                ('se_vende', models.BooleanField(default=False)),
                ('es_inventariable', models.BooleanField(default=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'hotels_productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('nro_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingresa', models.DateTimeField()),
                ('fecha_sale', models.DateTimeField()),
                ('titular', models.CharField(blank=True, max_length=255, null=True)),
                ('pax', models.IntegerField()),
                ('childs', models.IntegerField(default=0)),
                ('tarifa_noche', models.FloatField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Activa', 'Activa'), ('Cancelada', 'Cancelada'), ('Cerrada', 'Cerrada')], max_length=255)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'hotels_reservas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_state', models.CharField(max_length=255)),
                ('state_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'controlpanel_states',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='saldos_banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.FloatField()),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='andinasoft.cuentas_pagos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='gastos_caja',
            fields=[
                ('id_gasto', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_gasto', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('valor', models.IntegerField()),
                ('soporte', models.FileField(upload_to='gastos_cajas')),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('valor_iva', models.FloatField(blank=True, null=True)),
                ('valor_rte', models.FloatField(blank=True, null=True)),
                ('rte_asumida', models.BooleanField(blank=True, null=True)),
                ('estado', models.CharField(default='Pendiente', max_length=255)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concepto_gasto', to='accounting.conceptos_legalizacion')),
                ('cuenta_iva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_iva_gasto', to='accounting.impuestos_legalizacion')),
                ('cuenta_rte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_rte_gasto', to='accounting.impuestos_legalizacion')),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='andinasoft.cuentas_pagos')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tercero_gasto', to='accounting.partners')),
                ('usuario_aprueba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_aprueba_gasto', to=settings.AUTH_USER_MODEL)),
                ('usuario_carga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_carga_gasto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto de caja',
                'verbose_name_plural': 'Gastos de caja',
            },
        ),
    ]
