# Generated by Django 3.2.16 on 2024-07-17 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0062_anticipos_hotels_cities_cliente_consumos_countries_dias_de_sol_facturas_hoteles_forma_pago_alttum_ga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos_caja',
            name='soporte',
            field=models.FileField(upload_to='Cajas/Gastos'),
        ),
        migrations.CreateModel(
            name='reembolsos_caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicita', models.DateField(auto_now_add=True)),
                ('valor', models.IntegerField()),
                ('fecha_aprueba', models.DateField(blank=True, null=True)),
                ('doc_legalizacion', models.CharField(blank=True, max_length=255, null=True)),
                ('soporte_legalizacion', models.FileField(upload_to='Cajas/Legalizacion')),
                ('pago_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.pagos')),
                ('usuario_aprueba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_aprueba_reemb', to=settings.AUTH_USER_MODEL)),
                ('usuario_solicita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_solicita_reemb', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gastos_caja',
            name='reembolso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.reembolsos_caja'),
        ),
    ]
