# Generated by Django 3.2.16 on 2024-07-22 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0063_auto_20240717_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='reembolsos_caja',
            name='caja',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.PROTECT, to='andinasoft.cuentas_pagos'),
            preserve_default=False,
        ),
    ]
