# Generated by Django 3.2.16 on 2024-07-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0064_reembolsos_caja_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='reembolsos_caja',
            name='valor_a_reembolsar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
