# Generated by Django 3.2.16 on 2024-07-25 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0065_reembolsos_caja_valor_a_reembolsar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reembolsos_caja',
            name='pago_asociado',
        ),
        migrations.AddField(
            model_name='reembolsos_caja',
            name='transferencia_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.transferencias_companias'),
        ),
    ]
