# Generated by Django 3.2.16 on 2024-07-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0066_auto_20240725_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='apellidos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
