# Generated by Django 3.2.16 on 2024-07-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0067_alter_partners_apellidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='soporte_identificacion',
            field=models.FileField(blank=True, null=True, upload_to='Proveedores'),
        ),
    ]
