# Generated by Django 3.2.16 on 2024-08-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0068_partners_soporte_identificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldos_cuentas_tesoreria',
            name='saldo_teorico',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
