# Generated by Django 3.2.16 on 2025-03-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0069_saldos_cuentas_tesoreria_saldo_teorico'),
    ]

    operations = [
        migrations.CreateModel(
            name='parametros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, unique=True)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
    ]
