# Generated by Django 3.2.16 on 2025-03-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0070_parametros'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametros',
            name='valor',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
    ]
