# Generated by Django 3.2.16 on 2026-01-06 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andinasoft', '0069_add_upload_movements_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0076_add_proyecto_asociado_agente'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_movements_job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('partial', 'Parcialmente completado')], default='pending', max_length=20)),
                ('tiene_banco', models.BooleanField(default=False)),
                ('tiene_wompi', models.BooleanField(default=False)),
                ('tiene_plink', models.BooleanField(default=False)),
                ('movimientos_banco', models.IntegerField(blank=True, help_text='Movimientos de banco procesados', null=True)),
                ('movimientos_wompi', models.IntegerField(blank=True, help_text='Movimientos de Wompi procesados', null=True)),
                ('movimientos_plink', models.IntegerField(blank=True, help_text='Movimientos de Plink procesados', null=True)),
                ('movimientos_rechazados', models.IntegerField(blank=True, help_text='Movimientos rechazados', null=True)),
                ('archivo_rechazados', models.TextField(blank=True, help_text='Base64 del archivo de rechazados', null=True)),
                ('nombre_archivo_rechazados', models.CharField(blank=True, max_length=255, null=True)),
                ('mensaje', models.TextField(blank=True, help_text='Mensaje de resultado', null=True)),
                ('error_detail', models.TextField(blank=True, help_text='Detalle del error si falla', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andinasoft.empresas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trabajo de Carga de Movimientos',
                'verbose_name_plural': 'Trabajos de Carga de Movimientos',
                'ordering': ['-created_at'],
            },
        ),
    ]
