# Generated by Django 3.2.16 on 2026-03-03 20:16

import accounting.models
import andina.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0077_add_upload_movements_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticipos',
            name='soporte_pago',
            field=models.FileField(blank=True, null=True, storage=andina.storage_backends.LocalMediaStorage(), upload_to='Anticipos/Soportes de pago'),
        ),
        migrations.AlterField(
            model_name='archivo_contable',
            name='document',
            field=models.FileField(storage=andina.storage_backends.LocalMediaStorage(), upload_to=accounting.models.upload_to),
        ),
        migrations.AlterField(
            model_name='egresos_contable',
            name='soporte_egreso',
            field=models.FileField(blank=True, null=True, storage=andina.storage_backends.LocalMediaStorage(), upload_to='Facturas/Egresos contables'),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='soporte_causacion',
            field=models.FileField(blank=True, null=True, storage=andina.storage_backends.LocalMediaStorage(), upload_to='Facturas/Causacion'),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='soporte_radicado',
            field=models.FileField(blank=True, null=True, storage=andina.storage_backends.LocalMediaStorage(), upload_to='Facturas/Facturas'),
        ),
        migrations.AlterField(
            model_name='gastos_caja',
            name='soporte',
            field=models.FileField(storage=andina.storage_backends.LocalMediaStorage(), upload_to='Cajas/Gastos'),
        ),
        migrations.AlterField(
            model_name='legalizacion_anticipos',
            name='soporte',
            field=models.FileField(storage=andina.storage_backends.LocalMediaStorage(), upload_to='legalizaciones_anticipos'),
        ),
        migrations.AlterField(
            model_name='otros_ingresos',
            name='soporte',
            field=models.FileField(blank=True, null=True, storage=andina.storage_backends.LocalMediaStorage(), upload_to='Otros Ingresos'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='soporte_pago',
            field=models.FileField(blank=True, null=True, storage=andina.storage_backends.LocalMediaStorage(), upload_to='Facturas/Soportes de pago'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='soporte_identificacion',
            field=models.FileField(blank=True, null=True, storage=andina.storage_backends.LocalMediaStorage(), upload_to='Proveedores'),
        ),
        migrations.AlterField(
            model_name='reembolsos_caja',
            name='soporte_legalizacion',
            field=models.FileField(storage=andina.storage_backends.LocalMediaStorage(), upload_to='Cajas/Legalizacion'),
        ),
        migrations.AlterField(
            model_name='transferencias_companias',
            name='soporte_pago',
            field=models.FileField(blank=True, null=True, storage=andina.storage_backends.LocalMediaStorage(), upload_to='Transferencias/Soportes de pago'),
        ),
    ]
