# Generated by Django 3.2.16 on 2026-05-19 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('andinasoft', '0072_empresas_alegra'),
        ('accounting', '0080_fix_alegra_bill_deleted_mysql_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='gasto_aprobacion_comentario_contable',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='facturas',
            name='gasto_aprobacion_estado',
            field=models.CharField(choices=[('pendiente_asignacion', 'Pendiente asignación'), ('pendiente_aprobacion', 'Pendiente aprobación'), ('aprobado', 'Aprobado'), ('no_aplica', 'No aplica')], db_index=True, default='no_aplica', max_length=32),
        ),
        migrations.AddField(
            model_name='facturas',
            name='gasto_aprobado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='facturas',
            name='gasto_aprobado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturas',
            name='gasto_aprobado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_gasto_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facturas',
            name='gasto_aprobador_asignado',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_gasto_pendiente_aprobar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facturas',
            name='gasto_asignado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturas',
            name='gasto_asignado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_gasto_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GastoAprobador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, help_text='Vacío = puede aprobar gastos de cualquier empresa.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gasto_aprobadores', to='andinasoft.empresas')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='gasto_aprobador_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aprobador de gasto Alegra',
                'verbose_name_plural': 'Aprobadores de gasto Alegra',
            },
        ),
        migrations.AddConstraint(
            model_name='gastoaprobador',
            constraint=models.UniqueConstraint(fields=('user', 'empresa'), name='unique_gasto_aprobador_user_empresa'),
        ),
    ]
