# Generated by Django 3.2.16 on 2026-05-22 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('andinasoft', '0073_empresas_alegra_gasto_max_sin_aprobador'),
        ('accounting', '0086_pagos_alegra_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoContableNotificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='gasto_contable_notificaciones', to='andinasoft.empresas')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='gasto_contable_notificacion_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación contable gasto Alegra',
                'verbose_name_plural': 'Notificaciones contables gasto Alegra',
            },
        ),
        migrations.AddConstraint(
            model_name='gastocontablenotificacion',
            constraint=models.UniqueConstraint(fields=('user', 'empresa'), name='unique_gasto_contable_notif_user_empresa'),
        ),
    ]
