# Generated by Django 3.2.16 on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0087_gasto_contable_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastoaprobador',
            name='telefono',
            field=models.CharField(
                blank=True,
                default='',
                help_text='WhatsApp / SMS para n8n (ej. 573001234567, sin +).',
                max_length=32,
            ),
        ),
    ]
